### ISSUE TITLE
tiki_shared.h: boneType

### ISSUE THREAD

**Issue by EndlessEden** [openmoh/openmohaa#1]
field ‘boneType’ has incomplete type 'enum boneType_e enum boneType_e boneType'
tiki_shared.h:255:18 (enum boneType_e boneType) no defines, are specified. Please fix.

**Comment by Ley0k** [comment]
I think it has been fixed, tell me if you encounter any issues.

**Comment by kwadroke** [comment]
I just had the same issue. Recent pull.

**Comment by netpipe** [comment]
easy way to find the code would be to put it into codeblocks and see where the header file is ? i also have http://irrlicht.sourceforge.net/forum/viewtopic.php?f=6&t=52670 most recent version there is a mohaa loader in the IrrlichtDemos repository

**Comment by netpipe** [comment]
from a fresh checkout this issue still exists.

**Comment by netpipe** [comment]
https://github.com/netpipe/Luna i have started a new port until this issue gets fixed
![Screenshot at 2022-01-25 18-23-34](https://user-images.githubusercontent.com/172564/151097390-cbc8f124-b469-4d3a-88bd-14d6e3a83fe1.png)
.

**Comment by netpipe** [comment]
i also have a working version https://github.com/netpipe/IrrMOHAA here but it might be outdated

**Comment by netpipe** [comment]
https://github.com/EndlessEden/OpenMOHAA is what it was

**Comment by optimus-code** [comment]
@netpipe I'm not working on this project but I feel the need to say this: I mean no offense here but your posts are mostly irrelevant to the subject matter. Posting images of your own port of another engine has no place being here. This project specifically aims to be a swap-in replacement using the exact same technologies that were a foundation for the original MoH:AA engine (based on FAKK2 modified Quake 3 engine). 

If you have something to offer particularly on TIKI loading then it would be great if you could share your specific learnings.

It's great to see people working with MoH:AA but your posts do not really help this project along and your repo is obfuscated by the fact it's a completely different engine.

**Comment by Ley0k** [comment]
> im not sure you realize this but this bug has been present for over 5 years... its not going to get fixed. its better we have a working compile and a way to have fun with our media

This isn't a Facebook post, there is no need to comment about how you aren't going to help, nor need to advertise your project, it's not contributing to the project, thanks
