### ISSUE TITLE
(SH & BT) main menu flashing square grid textures

### ISSUE THREAD

**Issue by bulldozerecske** [openmoh/openmohaa#102]
These textures can be seen for short while after launch and going to multiplayer menu and before close.
![image](https://github.com/openmoh/openmohaa/assets/8028500/604d11ba-d783-44c8-a289-3a7b86a792c3)

**Comment by rsantellan** [comment]
For me happens a really wierd thing that is like an old tv with bad reception, black strips go through the window. If I alt+tab they go away, I try to record it but is all black. I will try to make a record to show.
