### ISSUE TITLE
(Spearhead) invisible player skins (models)

### ISSUE THREAD

**Issue by bulldozerecske** [openmoh/openmohaa#104]
DE - Waffen Shutze and DE - Waffen Officer skins (models) are not visible in Multiplayer Options.
![image](https://github.com/openmoh/openmohaa/assets/8028500/f743e3db-65b9-4974-9f8e-7f7b488e5105)

**Comment by smallmodel** [comment]
Fixed in commit 840501c8dd9f9ddedad907e7f3e33162d2d7c8b2
