### ISSUE TITLE
(BT - e1l1) jeep wrong path, wrong view

### ISSUE THREAD

**Issue by bulldozerecske** [openmoh/openmohaa#106]
On E1L1 (first mission, Tunisia) the path for the jeep is wrong. It moves through objects and goes offmap. After being killed and respawn, view is rotated 90 degress.
![image](https://github.com/openmoh/openmohaa/assets/8028500/0779ac7b-9236-4ce4-9a76-94bfd951f977)

**Comment by smallmodel** [comment]
Fixed in commit 796a3a711fc772082e5bbfc86421038d81ffffce
