### ISSUE TITLE
(Mohaa - m4|2) Openmohaa crashes after loading a game

### ISSUE THREAD

**Issue by gbudny** [openmoh/openmohaa#114]
Hi

I noticed that Openmohaa crashes after loading the level m4|2.

https://gist.github.com/gbudny/0f42ce6318fc7c422073a8b9398056df

I uploaded a .dmp file to WeTransfer:

https://we.tl/t-1J7EHW98ZA

I can inform you that Mohaa has only two levels that I can't even load. One of them was almost completable in previous releases.
Unfortunately, Spearhead and Breakthrough have more similar issues.

There are a few levels in Mohaa where it crashes in specific locations, but I report them soon. The rest of them are probably other bugs with trucks, tanks, etc.

Overall, I'm positively surprised with the current state of single-player mode in Mohaa. It's more advanced than many other similar projects.

**Comment by smallmodel** [comment]
Specific sound bug fixed in commit f1e2a45520e2b7feeaabc9c3675d689828b96938

**Comment by gbudny** [comment]
Hi

Thank you that you decided to re-open this issue.

I used the most recent version of OpenMoHAA, and below are files from the level m1|1:

https://gist.github.com/gbudny/ebd0f56a9f396ea1cf93f22fa8a6046c

I uploaded a file .dmp to WeTransfer:

https://we.tl/t-rNYf8bq0iZ

Can you fix it?

Files for the level m4|2 are in the closed issue because I wanted to avoid any confusion:

https://github.com/openmoh/openmohaa/issues/114

**Comment by gbudny** [comment]
Thank you.

I tested it, and I can complete all objectives at this level.
