### ISSUE TITLE
(Mohaa - M1|3a) The jeep gets stuck on the road at the same place

### ISSUE THREAD

**Issue by gbudny** [openmoh/openmohaa#116]
Hi

I want to inform you that I couldn't finish level M1|3a. The jeep always gets stuck on this road at the same place.

Can you fix it?

![Tooltip_007](https://github.com/openmoh/openmohaa/assets/13519111/debd12ae-639d-413a-8e2e-63c0b712f23e)

![Tooltip_008](https://github.com/openmoh/openmohaa/assets/13519111/fededa06-a7eb-49eb-8f16-ee2175eb6c74)

**Comment by smallmodel** [comment]
Should be fixed now (commit aa209e0aaf5c5ab8aa1e3e36b4d45bc52fdde264)

**Comment by gbudny** [comment]
Thank you.

I can complete this level now.
