### ISSUE TITLE
(Mohaa - M6|1c) Mike Powell is unarmed

### ISSUE THREAD

**Issue by gbudny** [openmoh/openmohaa#118]
Hi

I noticed that in the level M6|1c don't have any guns or a grenade at the beginning of it.

Can you fix it?

![Tooltip_012](https://github.com/openmoh/openmohaa/assets/13519111/ebbcc347-1a3f-44cf-8553-a0044410010c)

**Comment by smallmodel** [comment]
Should be fixed by b8e8aead93c19e7f2cd0e0d3c693ee1a5c4e52cd

**Comment by gbudny** [comment]
Thank you.

It works now.

I can also see that objectives work and this mission is completable. The game crashes when I lose, but I report this bug tomorrow.
