### ISSUE TITLE
(Mohaa - mohdm2 - Destroyed Village) - Terrain Collision Issue (Invisible wall)

### ISSUE THREAD

**Issue by optimus-code** [openmoh/openmohaa#119]
Hi

Playing Destroyed Village I seem to encounter a sort of collision bug at the location of the screenshot. I think it's related to the angle of the terrain potentially as this area has a bit of a gradient and a crater. In normal MoH:AA you do not get stuck here.

![image](https://github.com/openmoh/openmohaa/assets/12039578/c9190562-82bd-4d79-9f5c-412a6c08b38e)

**Comment by bulldozerecske** [comment]
and here:
![image](https://github.com/openmoh/openmohaa/assets/8028500/a8545ab8-4a8f-4d30-abdb-cf0445a05d77)

**Comment by bulldozerecske** [comment]
and here... looks like a global issue
![image](https://github.com/openmoh/openmohaa/assets/8028500/b9096f28-03f7-4548-8ec6-e1254133eeb3)

**Comment by smallmodel** [comment]
Fixed in commit 748934edcd35e3bde7506f676a1aabbdffaab81a
