### ISSUE TITLE
idtech 3 game engine experts - suggestion

### ISSUE THREAD

**Issue by cr0ssmind** [openmoh/openmohaa#12]
Hello Guys!
It is not issue, but a help. There is a good guys who develop OpenJA - the open source Jedi Academy. They have huge knowledge in developing idtech 3 engine. Ask them maybe on GitHub: **ensiform**, **xycaleth**, **eezstreet**, **Razish**

**Comment by mohabhassan** [comment]
Thanks a lot mate, But we're not stuck in understanding the engine, it's just that there are not a lot of people active here and we're not sure whether to continue the reversing route or implement stuff by ourselves (aka recreate mohaa).
But thanks for the help appreciated :).

**Comment by cr0ssmind** [comment]
Hello Dude,
you are welcome! I'am also a fan of the game and investigated deeply. First I tought that Jedi Academy and MOHAA has the same engine, but not. Both have individual "flavours" - I'am thinking here for Ghoul2 animation vs. FAKK animation system, etc...

I read the "drama" about source code release here: https://www.x-null.net/forums/threads/753-mohaa-source-code/page30

After 2 years, can we maybe ping the stakeholders about releasing the source code? Do you see any chance?

**Comment by mohabhassan** [comment]
Well it's defo not only 2 years, there were other attempts way before 2016. All of them were unsuccessful.
If there's something I've learned from all those attempts, it's that it's not gonna happen.
It kinda affects EA business scheme in some way.
Besides, OpenMOHAA serverside is only missing Actors and Vehicles which are both used in single player. Multiplayer is all ok and working.
We've come this far yes :)
I've been focusing lately on opm, I'm currently trying to implement actors and test lots of serverside mods to gain stability.

But enough talking about opm,
There's also a wider audience for a better project. mohue4/nextgenmoh/mohrises.
It's basically mohaa built on ue4, you can check out more on the discord server https://discord.gg/U5b6rXq .
