### ISSUE TITLE
(Mohaa m1|1) OpenMoHAA crashes after loading the first mission of Arzew

### ISSUE THREAD

**Issue by gbudny** [openmoh/openmohaa#120]
Hi

Thank you for trying to fix it.

Unfortunately, I checked the most version, and OpenMoHAA crashes after loading the level m1|1.

https://gist.github.com/gbudny/7f8a5a38332ede6756ed5da3fe582e62

Can you fix it?

I uploaded a .dmp file to Wetransfer:

https://we.tl/t-wd6p3KMQpZ

**Comment by smallmodel** [comment]
Same as #114, resolved

**Comment by gbudny** [comment]
Hi

Thank you for the answer.

I use the version of OpenMoHHA that you published today:

https://github.com/openmoh/openmohaa/tree/9ab28dc7da8f6f1db31090678475e236776ca78ff

Unfortunately, I can confirm that the game always crashes when I try to load the level m1|1 and m4|2.

Can you look at these issues again?

Should I create new issues for these levels?

**Comment by smallmodel** [comment]
Reupload new logs file, this must be a different cause for the crash

**Comment by gbudny** [comment]
Hi

Thank you that you decided to re-open this issue.

I used the most recent version of OpenMoHAA, and below are files from the level m1|1:

https://gist.github.com/gbudny/ebd0f56a9f396ea1cf93f22fa8a6046c

I uploaded a file .dmp to WeTransfer:

https://we.tl/t-rNYf8bq0iZ

Can you fix it?

Files for the level m4|2 are in the closed issue because I wanted to avoid any confusion:

https://github.com/openmoh/openmohaa/issues/11

**Comment by gbudny** [comment]
Thank you.

It works now,
