### ISSUE TITLE
Black seams on sky box edges

### ISSUE THREAD

**Issue by optimus-code** [openmoh/openmohaa#122]
When I use any build the skybox shows black seams on the edges. I modified "DrawSkySide" in tr_sky.c to set the texture mode to clamp as this kind of behaviour is typically caused by WRAP. 

`qglTexParameteri( GL_TEXTURE_2D, GL_TEXTURE_WRAP_S, GL_CLAMP_TO_EDGE );
qglTexParameteri( GL_TEXTURE_2D, GL_TEXTURE_WRAP_T, GL_CLAMP_TO_EDGE );`

When adding this, there is no longer a seam on the Skybox and they show correctly.

**Comment by smallmodel** [comment]
set `r_forceClampToEdge` to 1 and it must fix black seams
