### ISSUE TITLE
(Mohaa - m6|1c) Press fire to continue - the game crashes when Mike Powell dies

### ISSUE THREAD

**Issue by gbudny** [openmoh/openmohaa#125]
Hi

I noticed this issue is always happening in level m6|1c when Mike Powell dies. In this case, I try to click the left mouse button to reload this level, but it crashes at this point.

![Tooltip_013](https://github.com/openmoh/openmohaa/assets/13519111/018b7bb4-0a83-4728-849f-0f1ee41df0d3)

https://gist.github.com/gbudny/5b8cf5f0091006db78009bb17299a458

I uploaded a .dmp file to WeTransfer:

https://we.tl/t-vMrzK2BKaR

Can you fix it?

**Comment by smallmodel** [comment]
Fixed in 5a447405927cf8383f25c2773cb2f90f99d0d278

**Comment by gbudny** [comment]
Thank you.

OpenMoHAA doesn't crash at this point anymore in the level m6|1c and m2|3.
