### ISSUE TITLE
(AA) respawn timer

### ISSUE THREAD

**Issue by bulldozerecske** [openmoh/openmohaa#126]
In AA you should not have a respawn timer when you comit suicide (by default, at least).
![image](https://github.com/openmoh/openmohaa/assets/8028500/1d57171a-4e59-4645-accb-8b3e3337906c)

**Comment by smallmodel** [comment]
Fix 97a0bd90ec8b72ca4de4f8a8ab6937c9bc2cd26b
make sure to remove `sv_team_spawn_interval` from unnamedsoldier.cfg as well
