### ISSUE TITLE
(Breakthrough - e2|1) Locate and destroy anti-aircraft artillery (6 remaining) 

### ISSUE THREAD

**Issue by gbudny** [openmoh/openmohaa#128]
Hi

I noticed that I couldn't plant all explosives in the level e2|1 to complete the first objective: Locate and destroy anti-aircraft artillery (6 remaining). 

I can do the next two objectives, but I couldn't continue playing without the first one.

Can you fix it?

![Tooltip_014](https://github.com/openmoh/openmohaa/assets/13519111/273afa9d-78f8-45c7-ba77-5411f378d8c4)

**Comment by smallmodel** [comment]
Fixed in commit 45f50cfe2528d6d06c96d1933eb93e365223d1b5

![image](https://github.com/openmoh/openmohaa/assets/15067410/bbe877a4-a85d-45b4-adf8-4cfde3ca49b3)

**Comment by gbudny** [comment]
Thank you.

I can complete all objectives at this level.
