### ISSUE TITLE
(Spearhead - t3|1) Jack Barnes is unarmed

### ISSUE THREAD

**Issue by gbudny** [openmoh/openmohaa#129]
Hi

I noticed that in the level t3|1 don't have any guns at the beginning of it.

Can you fix it?

![Tooltip_015](https://github.com/openmoh/openmohaa/assets/13519111/714fcaf9-426f-4780-a4b5-e7336f6e9fcd)

**Comment by smallmodel** [comment]
Fixed in commit eb70b30e7a78cab38c7a19241690c9532fef55df

**Comment by gbudny** [comment]
Thank you.

I can complete all objectives at this level.
