### ISSUE TITLE
(Mohaa - m5|1b) Random crashes in Openmohaa when I try to destroy the tank

### ISSUE THREAD

**Issue by gbudny** [openmoh/openmohaa#130]
Hi

I want to inform you that the game always crashes when I try to destroy a tank in the level m5|1b. It happens in random places around this area where the tank is driving. I don't know if it's because I can't destroy it (probably a bug) or an other issue.

https://gist.github.com/gbudny/c35827457d3472f99c98cd1f12373acb

I uploaded a .dmp file to WeTransfer:

https://we.tl/t-gJw6U8tYyc

Can you fix it?

**Comment by smallmodel** [comment]
Fixed in commit 373a35acf0dc4d48db4c0eff776183e9b72d0bc5

**Comment by gbudny** [comment]
Thank you. 

It works now.

**Comment by bulldozerecske** [comment]
I've recently got a random crash.
