### ISSUE TITLE
(Mohaa - m5|2a and m5|2b) The tank floats above the ground

### ISSUE THREAD

**Issue by gbudny** [openmoh/openmohaa#132]
Hi

I want to inform you that I noticed the same issue with a tank in the level m5|2a and m5|2b. The tank starts to float above the ground shortly after playing it, and I can't do anything to stop it.

Can you fix it?

m5|2a

![Tooltip_017](https://github.com/openmoh/openmohaa/assets/13519111/c114c9f0-d6b4-42a9-9db8-b544b190c157)

m5|2b

![Tooltip_018](https://github.com/openmoh/openmohaa/assets/13519111/5c79cc4d-6fd4-48c2-9f8f-fb979c328fbd)

**Comment by smallmodel** [comment]
It was fixed in commit bf27caa61e6f51eb56425a6b562b96362d685b58

**Comment by gbudny** [comment]
Thank you.

It works now.
