### ISSUE TITLE
(Mohaa m5|3) Calling in artillery strikes doesn't work correctly

### ISSUE THREAD

**Issue by gbudny** [openmoh/openmohaa#133]
Hi

I want to inform you that I can't finish level m5|3. There are issues with calling artillery strikes. Tanks aren't destroyed quickly enough when I call in artillery strikes. Later, they merge, which probably makes it more difficult to destroy them.

Can you fix it?

![Tooltip_019](https://github.com/openmoh/openmohaa/assets/13519111/d07ca443-edde-44a6-832e-162f44d22689)

**Comment by gbudny** [comment]
It works much better now.

I was able to complete it a few times. Unfortunately, tanks still are not destroyed quickly enough when I call in artillery strikes. It doesn't work as in the original version of the game.

Can you improve it?

**Comment by smallmodel** [comment]
It should be working better now

**Comment by gbudny** [comment]
Thank you.
