### ISSUE TITLE
(SH & BT) Grenade Rifle texture and animation

### ISSUE THREAD

**Issue by bulldozerecske** [openmoh/openmohaa#136]
Incorrect animations for grenade rifle in both SH and BT. Missing texture in SH.
![image](https://github.com/openmoh/openmohaa/assets/8028500/a2dd3f0b-b635-4636-89e9-871e8fb8dd3a)

**Comment by smallmodel** [comment]
Fixed in e8109076f489badd3f28c25e8ccf18bae86d58da
