### ISSUE TITLE
(SH & BT - Druckkammern) non-solid ramps

### ISSUE THREAD

**Issue by bulldozerecske** [openmoh/openmohaa#151]
If you want to board to the uboat, you fall into the water because the ramps are non-solid:
![image](https://github.com/openmoh/openmohaa/assets/8028500/8d82d729-d237-4d71-8ef8-8db2ba6120d4)

**Comment by smallmodel** [comment]
Fixed in cf1dbf07c75095fc3675344967af0cd55b9efc95
