### ISSUE TITLE
(SH & BT - Druckkammern) incorrect bullet hit effect

### ISSUE THREAD

**Issue by bulldozerecske** [openmoh/openmohaa#152]
On Druckkammern, if you shoot the water, you get a metal a bullet hit effect:
![image](https://github.com/openmoh/openmohaa/assets/8028500/ab8c4b71-a659-49bd-864c-ff249987f860)

**Comment by smallmodel** [comment]
Fixed in 5cc599984d50b0bdcec136214bddedadaebfe1ec
