### ISSUE TITLE
(SH & BT - Berlin) non-solid terrain

### ISSUE THREAD

**Issue by bulldozerecske** [openmoh/openmohaa#154]
You can fall off the map (get killed) at this spot:
![image](https://github.com/openmoh/openmohaa/assets/8028500/403e715d-5124-4144-b600-7eb997e819cf)

and you can also see there are some gaps in the terrain model

**Comment by smallmodel** [comment]
Fixed in cf1dbf07c75095fc3675344967af0cd55b9efc95
