### ISSUE TITLE
(SH & BT) weapon switch animation glitch (rifle to pistol)

### ISSUE THREAD

**Issue by bulldozerecske** [openmoh/openmohaa#155]
This one exists in vanilla, too. When you switch from rifle (Mosin-Nagant) or sniper rifle (SVT 40) to pistol (Nagant Revolver) with mouse wheel, player's hand and the weapon holstering are not syncronized. Pistol appears before left hand goes hidden.
![image](https://github.com/openmoh/openmohaa/assets/8028500/cda3aefb-a783-46c0-8f90-286323c1ed2d)

**Comment by smallmodel** [comment]
Fixed in 500c70016f944f76c342a7f4da396e9a0b593b5d
