### ISSUE TITLE
(SH & BT - Flughafen) misplaced stuka

### ISSUE THREAD

**Issue by bulldozerecske** [openmoh/openmohaa#162]
Stuka is not placed correctly in OpenMohaa:
![image](https://github.com/openmoh/openmohaa/assets/8028500/6768a5c4-c488-4acb-994f-864303ce3eed)

**Comment by smallmodel** [comment]
It works for me

![shot](https://github.com/openmoh/openmohaa/assets/15067410/89722645-970b-4955-b449-612cd15ed9f7)

**Comment by smallmodel** [comment]
#272

**Comment by bulldozerecske** [comment]
I checked it again and now it is ok for me, too. One of the commits probably fixed this issue.
