### ISSUE TITLE
(SH & BT - Bizerte Festung) missing crate explosion fx

### ISSUE THREAD

**Issue by bulldozerecske** [openmoh/openmohaa#167]
In vanilla, there is fx if this kind of crate explodes:
![image](https://github.com/openmoh/openmohaa/assets/8028500/4dadcdc9-9949-4c04-a1f2-650fce04a5e2)
![image](https://github.com/openmoh/openmohaa/assets/8028500/0a7742b8-6a88-4bc8-8f3b-537fec43cff9)

**Comment by smallmodel** [comment]
It was fixed I don't know by what commit, but it works:

![image](https://github.com/openmoh/openmohaa/assets/15067410/953a5c30-88ee-4406-88ad-945dd9fda7d2)
