### ISSUE TITLE
(SH & BT) low detailed tunnels

### ISSUE THREAD

**Issue by bulldozerecske** [openmoh/openmohaa#168]
There are some mesh? fit issues in tunnels (you can see it on Kasserine or Malta)
![image](https://github.com/openmoh/openmohaa/assets/8028500/40feb49e-bdcd-426c-9fe8-5c13e448f075)

**Comment by smallmodel** [comment]
Fixed in commit 5aa70d91f333f84b4b33fa54f5f4e1cf0613fae1
