### ISSUE TITLE
Z_TagMalloc, Negative or zero size 0 tag 11

### ISSUE THREAD

**Issue by bulldozerecske** [openmoh/openmohaa#179]
Started maps/dm/mp_stadt_dm.bsp (RBM gametype) as a Dedicated Server and console was flooded with this in the CleanupGame section:

`Z_TagMalloc, Negative or zero size 0 tag 11`

In vanilla, I get warnings instead. Same error, but different output?

```
WARNING: CM_PatchCollideFromGrid: Degenerate patch - no planes (-496 1048 124)-(-496 1116 164)
WARNING: CM_PatchCollideFromGrid: Degenerate patch - no facets (-496 1048 124)-(-496 1116 164)
[...]
```

**Comment by smallmodel** [comment]
This might have been fixed by 336ba6181e7750f62afbd7c2cc2da7ec33305643
