### ISSUE TITLE
Remagen turret clock

### ISSUE THREAD

**Issue by bulldozerecske** [openmoh/openmohaa#180]
In OpenMohaa, it's noon/midnight, in vanilla, it's ~6:08.
![image](https://github.com/openmoh/openmohaa/assets/8028500/b52dc383-4417-4f15-987c-18034c28cb27)
![image](https://github.com/openmoh/openmohaa/assets/8028500/de462467-84b1-4ade-b655-932e5b3a6502)

Could be dynamic. Server time?

**Comment by smallmodel** [comment]
Fixed in b848ee0fac8987bfe029319a589bbf559e049ee2
