### ISSUE TITLE
(Spearhead - t2|3) The Panzerschreck doesn't exist - the issue with objectives

### ISSUE THREAD

**Issue by gbudny** [openmoh/openmohaa#200]
Hi

I want to inform you about the issue with objectives at the level t2|3.
 
I had to use a cheat code (wuss) to complete the last two objectives at this level. In this case, I can't pick up the Panzerschreck from the ground because it doesn't exist.

Can you fix it?

![Tooltip_037](https://github.com/openmoh/openmohaa/assets/13519111/0dd96471-4296-4cb4-906d-4cace3dbd456)

**Comment by gbudny** [comment]
Hi

I checked the most recent version of OpenMOHAA, and it looks like I can pick up the panzerschreck from the ground. I can use it, but it is invisible on a ground and even in my hands.

Can you fix it?

![Tooltip_004](https://github.com/openmoh/openmohaa/assets/13519111/847fe308-58e3-48d1-9cc2-964d2ab8ed36)

**Comment by smallmodel** [comment]
Is it visible for you now? I see it:

![image](https://github.com/openmoh/openmohaa/assets/15067410/3d7d43f2-d687-494a-a53a-1b05784b5e2c)

**Comment by gbudny** [comment]
Hi

Thank you for the answer.

**Comment by gbudny** [comment]
Thank you.

The last commit fixed this issue.
