### ISSUE TITLE
(Breakthrough - e1|4) The German soldiers don't accept documents

### ISSUE THREAD

**Issue by gbudny** [openmoh/openmohaa#203]
Hi

I want to inform you that I have difficulties at the beginning of the level e1|4. One of the German soldiers asks me about my ID, but the other one starts shooting at the same time.

I tried to show the document before this question, but it had the same effect. In this case, I get killed whenever the soldier asks me about it.

**Comment by bulldozerecske** [comment]
I can confirm, this is an issue in AA, too.

**Comment by gbudny** [comment]
Thank you.

I can complete this level now.
