### ISSUE TITLE
(Spearhead - t2|4) OpenMoHAA crashes while loading the level

### ISSUE THREAD

**Issue by gbudny** [openmoh/openmohaa#206]
Hi

I want to inform you that I can't load the t2|4 level because OpenMoHAA crashes when I try to do it.

https://gist.github.com/gbudny/aa93f69b107315cd9ff1286696903b23

I uploaded the .dmp file to WeTransfer:

https://we.tl/t-f0Q7M43ZMl

Can you fix it?

**Comment by smallmodel** [comment]
Fixed in commit f46078965d1b3c95130fd0cc9f28f4e372044d69

**Comment by gbudny** [comment]
Thank you.

I can load this level now.
