### ISSUE TITLE
(Breakthrough - e1|2) The jeep always stops driving at the same place

### ISSUE THREAD

**Issue by gbudny** [openmoh/openmohaa#207]
Hi

I want to inform you that in level e1|2, the jeep always stops at the same place, and nothing happens after that.

Can you fix it?

![Tooltip_040](https://github.com/openmoh/openmohaa/assets/13519111/303369e3-18b4-42a8-9d24-298e93f6b591)

**Comment by smallmodel** [comment]
Fixed (commit 65b47a2b3a02390ec20f63170ab7dabee12481d8)

**Comment by gbudny** [comment]
Thank you.

It works now.
