### ISSUE TITLE
Current state of affairs

### ISSUE THREAD

**Issue by optimus-code** [openmoh/openmohaa#21]
Hi guys

What is the current state of affairs with openmohaa? 

Has there been any progress on UI? What makes the current client unusable? (I was under the impression MP was fully playable?)

**Comment by mohabhassan** [comment]
Hello,
It's nice to see there are still people interested in the project.
You can check the current roadmap here https://www.x-null.net/forums/threads/2495-Roadmap-New-OpenMoHAA-source-code
Here's the summary anyways:


 * Server Side
	 * Almost everything is finished
	 * Missing full vehicle code
	 * A few actor functions
	 * Implementing exceptions for both actor and vehicle (could be even more exceptions outside actor and vehicle that we missed)
	 *  Testing/stability checks
 * Client Side
	 * UI part is missing, it's huge though, larger than actor code.
	 * Some render related stuff missing.
	 * Some sound related stuff too.
	 *  Testing/stability checks

**Comment by optimus-code** [comment]
Hey

Thanks for the quick response. It's been many years since I delved into Quake programming but I'd be happy to offer any help where needed. I've registered on the forum but do not have permissions to view the Road Map.

The state is much more promising than I'd previously thought and I'd be happy to try push things along with UI (Will need to do a lot of research but I have had some success writing my own UI interpreter for MOHAA GUI files, albeit in C# and a Direct3D 11 basic engine)

I look forward to hearing from you.
Dan

**Comment by Ley0k** [comment]
Hello,

only class declarations in the UI library were decompiled, check https://github.com/openmoh/openmohaa/tree/master/code/uilib

The UI that MOH uses is actually part of FAKK2, unfortunately we don't have the source code portion for it otherwise it would have saved us a lot of time

**Comment by mohabhassan** [comment]
Oi,
I'd like to add to what ley0k said,
I don't really re-implement stuff, I decompile them (using automated tools ofc). Kinda takes the fun out of it but it's defo 10 times better than any other approach.
It also feels good to understand a set of functions after they're all decompiled.
So, would you be willing to join the decompiler squad ? or the lonewolf approach ?  :smile:

**Comment by optimus-code** [comment]
Some light reading to do then! I have noticed there is this notion around here that you have go fully one way or the other; I don't really agree that it should always be the case. 

Look at projects like openmw that have reinvented several aspects of core functionality of a game engine (while staying true to original function). Sometimes you have to recreate the wheel and use knowledge you gain via reverse engineering to help you get there; so I'm not a purist in this sense.

Just curious, is that basically where the community split is? And does openmohaa not allow work done on the engine unless it's purely reverse engineered and not just functionally similar?

**Comment by Ley0k** [comment]
The goal of OpenMoHAA is to make it fully retro-compatible with MOH:AA as well as being able to add new features, so there is no community split between MOH:AA players and OpenMoHAA players. You may refer to the [MOHUE](https://www.moh-rises.com/) project instead, which is not retro-compatible with MOH:AA assets and use a totally new engine/design.

Work on OpenMoHAA could be done as long as the code is clean (reverse engineered C, or C++ approach) and its functionality is similar to MOH:AA

**Comment by mohabhassan** [comment]
Just as ley0k said, we have np if you implement it. It's preferable though that you reverse it.

**Comment by cr0ssmind** [comment]
Hello again,
Good to see this conversation after a year later. :-) I'am happily help you in testing both server and client side and maybe coding later. I never reverse engineered before, but I gladly help you if it can elevate progresses to a higher beats. Is there any Discord channel where we can communicate about plans and progresses?

**Comment by mohabhassan** [comment]
> 
> 
> Hello again,
> Good to see this conversation after a year later. :-) I'am happily help you in testing both server and client side and maybe coding later. I never reverse engineered before, but I gladly help you if it can elevate progresses to a higher beats. Is there any Discord channel where we can communicate about plans and progresses?

Hello again cr0ssmind,
We didn't really think about it before but we've just created a discord server.
https://discord.gg/NYtH58R

You can find latest invite link in readme.

**Comment by optimus-code** [comment]
Hey guys, I'm sure you already know this link but just incase; there is documentation for übertools which may help in reverse engineering parts of the feature set, it is quite basic though. (http://ritualistic.com/games/ef2/gdkdocs/start.html)
