### ISSUE TITLE
(AA - m5l1b) strange AI behaviour

### ISSUE THREAD

**Issue by bulldozerecske** [openmoh/openmohaa#230]
At the beginning of the level, one of the NPCs (should be a medic guy) is doing weird things. It has different uniform, it goes to landshark, it lies on stairs, does other funny animations. Sometimes the medic spawns correctly.

![image](https://github.com/openmoh/openmohaa/assets/8028500/b20172a1-0062-4750-a51d-0e541b1f3a5f)
![image](https://github.com/openmoh/openmohaa/assets/8028500/a4bbaae1-ff55-4043-aee3-c593d1e37503)
![image](https://github.com/openmoh/openmohaa/assets/8028500/5048782f-33a9-4149-90b9-7768c0261aef)
![image](https://github.com/openmoh/openmohaa/assets/8028500/70ad3c0f-8875-4ce4-a379-8918fa4a32c4)

**Comment by smallmodel** [comment]
It must be ok now
