### ISSUE TITLE
(AA - m2l3) missing sky 

### ISSUE THREAD

**Issue by bulldozerecske** [openmoh/openmohaa#235]
I went outside and....

![image](https://github.com/openmoh/openmohaa/assets/8028500/333e20a6-033d-418a-bd02-a294cc930762)

**Comment by gbudny** [comment]
Hi

I remember that I had this bug too, but below is a screenshot from the current version:

![Tooltip_004](https://github.com/openmoh/openmohaa/assets/13519111/2d38f489-92ca-4ff6-b252-b4931efb0841)

**Comment by smallmodel** [comment]
I forgot exactly when it was fixed and how but it seemed to be related to the lack of fog
