### ISSUE TITLE
crash after mission failed

### ISSUE THREAD

**Issue by bulldozerecske** [openmoh/openmohaa#239]
I was killed, mission failed screen appeared, clicked and client crashed.

```
CG_ModelAnim: Could not find parent entity
CG_ModelAnim: Could not find parent entity
Loading game...m3l30000
OPENMOHAA Archive Version 14
SV_ArchiveServerFile(false)
Channel memory manager started
------ Server Initialization ------
Server: m3l3
Gametype changed, clearing session data.
==== CleanupGame ====
```
![image](https://github.com/openmoh/openmohaa/assets/8028500/88c5afd9-5f3c-4e24-912c-80e93edec88a)

second attempt:
![image](https://github.com/openmoh/openmohaa/assets/8028500/66171c75-adb7-40c0-bd8c-6a18e5d9f7db)

**Comment by smallmodel** [comment]
Fixed in commit b76f9a9a6cf8aa950465b4874530ef4390588881
