### ISSUE TITLE
(SH - t3l2) missing sky

### ISSUE THREAD

**Issue by bulldozerecske** [openmoh/openmohaa#250]
The sky is missing on this level.

![image](https://github.com/openmoh/openmohaa/assets/8028500/b9835e54-bf96-42b5-94c0-38d56f32796a)

**Comment by smallmodel** [comment]
Commit e1f2433c36206e0852656f4d88c13b8bc738cd50 fixed it

**Comment by gbudny** [comment]
Hi

I checked it out and saw a part of the building in the sky.

Can you fix it?


![Tooltip_006](https://github.com/openmoh/openmohaa/assets/13519111/ea600812-c0ae-417a-a18e-3363b4954387)
