### ISSUE TITLE
(BT - e3l1) unmanned AA gun

### ISSUE THREAD

**Issue by bulldozerecske** [openmoh/openmohaa#257]
AA gun is not manned and is not shooting at aerial targets.

In vanilla, it works like this:
![image](https://github.com/openmoh/openmohaa/assets/8028500/3b3ea34d-292b-4d15-84ce-a62bce41e4cb)

**Comment by smallmodel** [comment]
It was fixed in commit cc721a3db630ca95fd870abfce50b504ce095418
