### ISSUE TITLE
(BT - Monte Cassino) missing sky

### ISSUE THREAD

**Issue by bulldozerecske** [openmoh/openmohaa#260]
Sky is black in OpenMohaa
![image](https://github.com/openmoh/openmohaa/assets/8028500/b77eb06d-b108-42e0-9a1f-90f0d94ea566)

while in Vanilla:
![image](https://github.com/openmoh/openmohaa/assets/8028500/b285ad12-d431-4f76-962b-d6cde896b7da)

**Comment by gbudny** [comment]
Hi

I checked it out, and this issue exists in the most recent version of OpenMoHAA.

Can you fix it?

**Comment by gbudny** [comment]
Thank you.

It works now.
