### ISSUE TITLE
(BT - e1l2) simultaneous interaction

### ISSUE THREAD

**Issue by bulldozerecske** [openmoh/openmohaa#262]
On this level, you need to destroy artillery cannons. If you place the explosive on them by pressing the USE button, you also use them. You need to get out before they explode.

![image](https://github.com/openmoh/openmohaa/assets/8028500/e7bdad28-ebc4-4421-888d-c77764ce3ab1)

**Comment by smallmodel** [comment]
Should be fixed by 58d0e43f78615e3262eb199a103431d948a9be79
