### ISSUE TITLE
unable to pick up ammo from dead NPCs

### ISSUE THREAD

**Issue by bulldozerecske** [openmoh/openmohaa#263]
Playing SP you can easily get low on ammo, because player does not receive any ammo from dropped weapons of dead NPCs.

![image](https://github.com/openmoh/openmohaa/assets/8028500/6009157f-28b6-419e-9138-0356c08d9666)

**Comment by smallmodel** [comment]
Fixed in commit 35e6435382379a2c6f7a49cae014f07e3709faf2
