### ISSUE TITLE
(BT - e1l2) missing mine detector UI

### ISSUE THREAD

**Issue by bulldozerecske** [openmoh/openmohaa#265]
Mine detector image is missing in OpenMohaa:
![image](https://github.com/openmoh/openmohaa/assets/8028500/5e8a78c6-3fdf-492a-bd74-7a50fb97e379)

In vanilla, it is present:
![image](https://github.com/openmoh/openmohaa/assets/8028500/92db809a-bce8-49bb-8ed3-afe97efb7b8d)

**Comment by gbudny** [comment]
Hi

I can confirm this issue exists in the most recent version of OpenMoHAA.

**Comment by gbudny** [comment]
Thank you.

It works now.
