### ISSUE TITLE
(BT - e1l2) no speech animation for NPCs

### ISSUE THREAD

**Issue by bulldozerecske** [openmoh/openmohaa#266]
closed mouth

![image](https://github.com/openmoh/openmohaa/assets/8028500/67c79232-ad90-4c3b-8e8a-a689d42c5700)

**Comment by gbudny** [comment]
Hi

I think this issue is fixed in the most recent version of OpenMoHAA. I could observe that his mouth is moving when he speaks. 

Of course, I can't observe the whole scene because a well-known flickering bug exists in the entire game. Sometimes, tanks are people are black if they move.

**Comment by bulldozerecske** [comment]
It is not an issue anymore. 
Tested on: OpenMoHAA 0.70.0-alpha+491.3733761 win_msvc64-x86_64 Sep 02 2024 UTC
