### ISSUE TITLE
SNDDMA exception

### ISSUE THREAD

**Issue by bulldozerecske** [openmoh/openmohaa#268]
OpenMoHAA 0.61.0-alpha+340.36af9e6 win_msvc64-x86_64 Feb 26 2024 UTC

Got an exception in skeletor_utilities.cpp (crash after mission failed bug) then I closed the console and clicked on continue, then I got another exception thrown:

![image](https://github.com/openmoh/openmohaa/assets/8028500/47dba954-e341-4f9c-bed7-8755b0e91e2e)

**Comment by smallmodel** [comment]
Not an issue anymore since the switch to OpenAL
