### ISSUE TITLE
(AA - m1l2a, SH - t2l2) truck & NPCs float in the air

### ISSUE THREAD

**Issue by bulldozerecske** [openmoh/openmohaa#272]
The truck and PoWs are floating in the air for a while at the first scene of this level.

![image](https://github.com/openmoh/openmohaa/assets/8028500/a285bbab-1d9f-4b87-8d8a-64c40809b72f)

**Comment by bulldozerecske** [comment]
Same issue in SH, on level t2l2:

![image](https://github.com/openmoh/openmohaa/assets/8028500/96a7f92f-4162-495a-b3d1-e6b9ce28f6de)

**Comment by smallmodel** [comment]
I believe this issue is fixed now
