### ISSUE TITLE
missing load game images

### ISSUE THREAD

**Issue by bulldozerecske** [openmoh/openmohaa#273]
In the Save / Load game menu, placeholder of ingame preview images is empty.

![image](https://github.com/openmoh/openmohaa/assets/8028500/1d328727-ca60-4464-94ca-ee77b431e0f2)

**Comment by gbudny** [comment]
Hi

I can confirm this issue exists in the most recent version of OpenMoHHA.

**Comment by gbudny** [comment]
Hi

Thank you for your decision to start working on it.

Unfortunately, I have some problems with these images, which I report in a separate issue.
