### ISSUE TITLE
(Breakthrough - e3|2) - The tank doesn't destroy a wall of a building 

### ISSUE THREAD

**Issue by gbudny** [openmoh/openmohaa#276]
Hi

I want to inform you that I can't continue playing at this level without cheat codes. In this case, the tank should destroy a wall of a building, but it doesn't happen in OpenMoHAA.  The tank completely ignores me even if I shoot to it.

Can you fix it?

![Tooltip_053](https://github.com/openmoh/openmohaa/assets/13519111/9efabb3e-e656-4fde-b4c6-1b615ed8c9d4)

![Tooltip_052](https://github.com/openmoh/openmohaa/assets/13519111/d127474a-2455-4989-bf48-acc41ce5cc00)

**Comment by gbudny** [comment]
Hi

The tank is now attacking the building, which is a nice progress. However, when the tank is shooting this wall doesn't get destroyed.

**Comment by smallmodel** [comment]
It's ok now (fixed in commit f39a4c0bc7c35159f49a941a1eb805751cb9a356)

**Comment by gbudny** [comment]
Thank you.

It works now.
