### ISSUE TITLE
missing bulletholes on blackwindows

### ISSUE THREAD

**Issue by bulldozerecske** [openmoh/openmohaa#278]
Broken glass type of bulletholes are missing on so called blackwindows.

![image](https://github.com/openmoh/openmohaa/assets/8028500/98deac21-22c3-4953-9a09-66177b3ebfcf)

**Comment by smallmodel** [comment]
Should work now
![image](https://github.com/openmoh/openmohaa/assets/15067410/7e40128a-4782-43fd-ae5b-31fe2f861088)
