### ISSUE TITLE
TODO: Implement CMake support

### ISSUE THREAD

**Issue by smallmodel** [openmoh/openmohaa#28]
The project currently uses Visual Studio solution files (Windows) and Eclipse project files (for Linux). Goal is to use CMake for the entire project instead, for easier contribution.

Must be able to target any platform on any architecture. C++17 standard at minimum should be used for convenience.

Possible binaries outputs:
- Server binaries: omohded**Arch** and game**Arch**
- Client binaries (of course the client can host a LAN game): openmohaa, cgame**Arch**

Maybe an option to be able to compile statically, resulting in fgame/cgame combined into the output executable?

**Comment by Ley0k** [comment]
## CMake structure suggestion

Start with CMakeLists.txt at the root

### Project CMakes

- **/code/cgame/CMakeLists.txt**: Client game module
- **/code/game/CMakeLists.txt**: Game module
- **/code/renderer/CMakeLists.txt**: Renderer
- **/code/server/CMakeLists.txt**: Server engine code
- **/code/uilib/CMakeLists.txt**: User interface library for the client

### Common CMakes:

CMake files that are commonly included by projects:

- **/code/bg/CMakeLists.txt**: common movement algorithm, between client and game, not sure what _bg_ means, there should be a better name for it
- **/code/globalcpp/CMakeLists.txt**: script stuff
- **/code/qcommon/CMakeLists.txt**: common stuff, should be merged with globalcpp?
- **/code/skeletor/CMakeLists.txt**: client and server code for animation and skeleton
- **/code/tiki/CMakeLists.txt**:  client and server code for TIKI
