### ISSUE TITLE
incorrect bulletholes for wooden materials

### ISSUE THREAD

**Issue by bulldozerecske** [openmoh/openmohaa#282]
Wooden materials have general bullethole textures, also.
![image](https://github.com/openmoh/openmohaa/assets/8028500/ae7cfb8f-d1f3-422f-af5a-2ce5e7c7287f)

In vanilla, it looks like this:
![image](https://github.com/openmoh/openmohaa/assets/8028500/3286c37d-78de-4869-b4aa-02a265fd1336)

**Comment by smallmodel** [comment]
#281
