### ISSUE TITLE
mohdm5 - no snowing

### ISSUE THREAD

**Issue by bulldozerecske** [openmoh/openmohaa#285]
It is not snowing in Snowy Park.
![image](https://github.com/openmoh/openmohaa/assets/8028500/c80feef0-6d2e-481f-bf6d-5e345dc0b37b)

In Vanilla, it is.
![image](https://github.com/openmoh/openmohaa/assets/8028500/8e46ba4b-9a65-4c54-84d9-ae20d2188ee4)

**Comment by smallmodel** [comment]
Fixed in e7cd70b8ee7ea8bc1e688c32a7ad3252ef581620 (set `cg_rain` to 1)

**Comment by bulldozerecske** [comment]
> Fixed in [e7cd70b](https://github.com/openmoh/openmohaa/commit/e7cd70b8ee7ea8bc1e688c32a7ad3252ef581620) (set `cg_rain` to 1)

It was "1" for me, updated binaries but still not snowing.
