### ISSUE TITLE
(Spearhead - t2|3) Escort medic to the captain - the medic runs in place below the ground

### ISSUE THREAD

**Issue by gbudny** [openmoh/openmohaa#291]
Hi 

I want to inform you that sometimes I can't complete the objective: escort medic to the captain in level t2|3. The medic drops below the ground and runs in place.

Can you fix it?

![Tooltip_003](https://github.com/openmoh/openmohaa/assets/13519111/c2aa824b-5ca6-4b62-8082-254b3c6a6a40)

**Comment by smallmodel** [comment]
This should be fixed by commit 5a8cc83e6ed2a3d16b8d125326662d69e09dcef2

**Comment by gbudny** [comment]
Thank you.

I tried several times to walk with the medic to the same location where I had this issue. It doesn't happen anymore.
