### ISSUE TITLE
(MoHAA - 5|2b) The game freezes in the middle of this level

### ISSUE THREAD

**Issue by gbudny** [openmoh/openmohaa#292]
Hi

I want to inform you that the last version of OpenMoHAA freezes in the middle of the level 5|2b. The game doesn't react to keystrokes or mouse clicks. I can only finish this process in the system. It usually happens somewhere in this place:

28:00

https://youtu.be/CNSUclbAXrU?list=PLp1mWA5o0CfRsbueWzjjpDJkhvBo2Fl3q

I uploaded the .dmp file and the output from a terminal.

https://we.tl/t-KYRCSjVbF3

Can you fix it?

**Comment by smallmodel** [comment]
The problem is `ter_maxtris` set to 16384 instead of 24576. The base game also has this issue

**Comment by gbudny** [comment]
> The problem is `ter_maxtris` set to 16384 instead of 24576. The base game also has this issue

Hi

Thank you for the answer.

I didn't have it in my config file, so I added seta ter_maxtris "24576".
This time, the game didn't crash in this place, and I could finish this level.

I didn't have this issue in previous versions, and it's not a part of the standard installation of OpenMoHHA.

Do you plan to add it?

I ask about it because I don't know if I should report issues with these new settings in a config files. It could cover similar bugs in other levels in the future.

**Comment by gbudny** [comment]
Hi

Thank you.

I removed the hidden .openmohaa folder and built a new version of OpenMoHAA.

I played it a few times, and it doesn't crash anymore.
