### ISSUE TITLE
(Spearhead - t2|3) Locate and defend the right flank - The German soldiers aren't coming 

### ISSUE THREAD

**Issue by gbudny** [openmoh/openmohaa#293]
Hi

I want to inform you that I can't complete the objective: locate and defend the right flank at this level. The German soldiers don't come to the right flank, and nothing happens.

I saw the same bug in the previous versions. However, It only happened after I lost and reloaded this level.

Can you fix it?

![Tooltip_005](https://github.com/openmoh/openmohaa/assets/13519111/099f97a3-b0ef-4432-a208-b68e67d49263)

**Comment by smallmodel** [comment]
This should be fixed by commit 5a8cc83e6ed2a3d16b8d125326662d69e09dcef2.
It was because the captain was falling under the map, the objective depends on the captain moving to the player.

**Comment by gbudny** [comment]
Thank you.

It works now.

I don't have this issue anymore.
