### ISSUE TITLE
No music and problems with other sounds

### ISSUE THREAD

**Issue by SilentMRG** [openmoh/openmohaa#296]
Hello...

In the main menu, music does not play and the sound of "drum beats" fails when selecting menu options. In training, the weapon sounds fail, and there is no sound when the grenade explodes. There is also no music in training or in the first mission, which also has the same sound bugs.

I think I installed it correctly? I moved the folders from my GOG installation to the newly created folder of the source port, following image:

![MoHAA](https://github.com/openmoh/openmohaa/assets/62117728/fdd99a90-127f-45e8-be85-94ac727a80b4)

Anyway, the only errors I've experienced so far concern the audio. Graphically I didn't notice any strangeness. I don't know if the "snddrivers" folder is necessary, I tested with it and without it and the audio errors were the same. And I'm using the latest nightly build.

Thank you and best regards!

**Comment by smallmodel** [comment]
Try by using artifacts from the latest GitHub Actions: https://github.com/openmoh/openmohaa/actions/runs/9054491075

**Comment by Alex3474247** [comment]
In the main menu, this track should play: mus_MainTheme.mp3

**Comment by SilentMRG** [comment]
The audio/music problem has been resolved! Tested on v0.70.0-windows-x64.
