### ISSUE TITLE
(Breakthrough - e2|2) The communication tower is invisible

### ISSUE THREAD

**Issue by gbudny** [openmoh/openmohaa#299]
Hi

I want to inform you that the communication tower is invisible in this level. I can set explosives, but it's tricky now.

I didn't have this issue in previous versions of OpenMoHAA.

Can you fix it?

![Tooltip_002](https://github.com/openmoh/openmohaa/assets/13519111/1809bd31-bc97-440a-a3e1-230caf7488a4)

**Comment by smallmodel** [comment]
Hello, unfortunately I'm not able to reproduce the issue, from the latest commit 98239050d892cf9d92997c448bcdb52024d3d46b:
![shot0016](https://github.com/openmoh/openmohaa/assets/15067410/bb53a946-09d0-4ddd-b590-e8c1aedc27c2)

`set sv_showentnums 1` to see if the entity tower appears:
![shot0018](https://github.com/openmoh/openmohaa/assets/15067410/a3cdaa4d-3d44-42fe-8579-33d7a8fc1752)

**Comment by gbudny** [comment]
Hi

Thank you for the answer.

I made a screenshot:

![Tooltip_001](https://github.com/openmoh/openmohaa/assets/13519111/1ee7e7f5-eef3-43f7-b475-a78ca936369b)

I can't see a communication tower, but it's there because I can't walk in this area even after the explosion.

It reminds me of this old bug in the training mission with the invisible tents and other objects:

https://github.com/openmoh/openmohaa/issues/69

**Comment by smallmodel** [comment]
What are the values of `r_lodcap`, `r_lodscale` and `lod_tool`? Try setting `r_uselod` to `0` temporarily

**Comment by gbudny** [comment]
> What are the values of `r_lodcap`, `r_lodscale` and `lod_tool`? Try setting `r_uselod` to `0` temporarily

> What are the values of `r_lodcap`, `r_lodscale` and `lod_tool`? Try setting `r_uselod` to `0` temporarily

Hi

Thank you for the answer

I only found these two parameters in the file omconfig.cfg

seta r_lodscale "5"
seta r_lodcap "0.35"

I don't have lod_tool in this file, but I can add it if I know the correct value.

Can you help me with it?

I added r_uselod to this file, but it doesn't change anything:

seta r_uselod "0"

I attached my config file from the maintt directory.

![Tooltip_003](https://github.com/openmoh/openmohaa/assets/13519111/b0dd8984-f78e-4bbe-a2b4-747a046398db)

**Comment by gbudny** [comment]
Thank you.

It works now.
