### ISSUE TITLE
Build Error: Hunk_Alloc

### ISSUE THREAD

**Issue by EndlessEden** [openmoh/openmohaa#3]
sv_bot.c: In function ‘BotImport_HunkAlloc’:
sv_bot.c:309:27: error: ‘h_high’ undeclared (first use in this function)
sv_bot.c:309:27: note: each undeclared identifier is reported only once for each function it appears in
sv_bot.c:309:9: error: too many arguments to function ‘Hunk_Alloc’
---

Please advise.

**Comment by Ley0k** [comment]
I haven't updated the project for msvc10. Can you try by using the VC2015 solution in misc\msvc12_13\openmohaa ?

**Comment by kwadroke** [comment]
Also got this error with Make on Linux

```
code/server/sv_bot.c: In function ‘BotImport_HunkAlloc’:
code/server/sv_bot.c:309:27: error: ‘h_high’ undeclared (first use in this function)
  return Hunk_Alloc( size, h_high );
```
