### ISSUE TITLE
(MoHAA/Spearhead/Breakthrough) The missing information about places and dates

### ISSUE THREAD

**Issue by gbudny** [openmoh/openmohaa#302]
Hi

I want to inform you that the information about dates and places isn't displayed before these levels:

**Medal of Honor**

m3|1a

**Spearhead**

t1|1
t2|1
t2|3
t2|4
t3|1

**Breakthrough**

e1|1
e2|1
e3|1
e3|3
e3|4

Can you fix it?

**Comment by smallmodel** [comment]
Hello, I need more clarification, when is the information shown?

**Comment by gbudny** [comment]
Hi

Thank you for the answer.

Every level is loaded, you can see subtitles with this information on a black screen, and then everything slowly starts to be visible. Later, subtitles with this information fade away.

For example, this is how it looks in m3|1a:

01:35:06 - 01:35:15
 
https://www.youtube.com/watch?v=ywfEfE_4KNs

**Comment by gbudny** [comment]
Thank you.

It works now.
