### ISSUE TITLE
(AA - m2l1) terrain does not fit

### ISSUE THREAD

**Issue by bulldozerecske** [openmoh/openmohaa#317]
Terrain does not fit at this location:

![image](https://github.com/openmoh/openmohaa/assets/8028500/dea2d283-2cfc-48e9-a9f8-701e6057ce8b)

Build: OpenMoHAA 0.62.0-alpha+400.9615faf win_msvc64-x86_64 Jul 01 2024 UTC

**Comment by smallmodel** [comment]
`r_subdivisions` may be too low, it should be set to at least 2

**Comment by bulldozerecske** [comment]
> `r_subdivisions` may be too low, it should be set to at least 2

You're right. Should be at least '2' by default, then. :)
