### ISSUE TITLE
(AA - m2l1) player block box missing

### ISSUE THREAD

**Issue by bulldozerecske** [openmoh/openmohaa#318]
You can pass by on the top edge of the bunker and get undermap at this location:

![image](https://github.com/openmoh/openmohaa/assets/8028500/5acdc377-8239-4b89-9d44-41b424ec495b)
![image](https://github.com/openmoh/openmohaa/assets/8028500/9e8cd169-f765-4b06-a918-1d3a28294111)

Build: OpenMoHAA 0.62.0-alpha+400.9615faf win_msvc64-x86_64 Jul 01 2024 UTC

**Comment by smallmodel** [comment]
Fixed by dca9709b122a32741a1df9edc72d96692f1208c5
