### ISSUE TITLE
(Mohaa - m6|3e) The game stutters when I get to a freight car

### ISSUE THREAD

**Issue by gbudny** [openmoh/openmohaa#324]
Hi

I want to inform you about the issue I noticed when getting into a freight car. At this moment, the game stops and starts to stutter for 2 - 3 seconds. Then, it continues to work normally.

Can you fix it?

**Comment by smallmodel** [comment]
It's due to the MP3 decoder (libmad) doing its work, maybe try compiling in Release mode instead, to optimize the code

**Comment by gbudny** [comment]
Hi

Thank you for the answer. 

I have the same issue after compiling OpenMoHAA in Release mode.

**Comment by smallmodel** [comment]
Merging into a single issue #333
