### ISSUE TITLE
(MoHAA/Spearhead/Breakthrough) Music doesn't work when I use save games and quick saves

### ISSUE THREAD

**Issue by gbudny** [openmoh/openmohaa#327]
Hi

I want to inform you that music works when I start every level in OpenMoHAA. However, the music stops working if I lose during this game and try to reload a level. It also happens when I quit this game and open it again with save games/quick saves. 

Can you fix it?

**Comment by smallmodel** [comment]
As stated in the above commit, the newer experimental sound system is required for this (OpenAL). To use the new sound system, a [special CMake flag](https://github.com/openmoh/openmohaa/blob/main/docs/compiling.md) is required.
