### ISSUE TITLE
The black screen and libmad errors when I use the parameter -DUSE_SOUND_NEW=1

### ISSUE THREAD

**Issue by gbudny** [openmoh/openmohaa#330]
Hi

I want to inform you that OpenMoHAA displays only a black screen when I use the parameter - DUSE_SOUND_NEW=1. I also noticed that music doesn't play when I use it.

I tried to compile it in Debug (even without all debug options) and Release mode (only with this parameter: -DUSE_SOUND_NEW=1). I tried to install libmad-dev, but it didn't help to solve this issue.

I noticed that limbad generates some errors and warnings when I use a parameter: -DUSE_SOUND_NEW=1. 

Can you help me solve this issue?

https://gist.github.com/gbudny/dd68d771194230a0ab4d2fc777f86094

**Comment by smallmodel** [comment]
You don't need `libmad-dev`, libmad is shipped with openmohaa. You will only need `libopenal-dev`.

I can't reproduce the issue on WSL nor a Raspberry Pi 5, you will need to pause debugger and send a call trace of the main thread

**Comment by gbudny** [comment]
Thank you for the answer.

I installed openal-dev when Cmake required it, and I removed libmad-dev when it didn't help me to solve it.

I try to use GDB as always, but I don't know if it's the correct way this time:

https://we.tl/t-9Xxb2USsk3

Main thread?

Do you think about thread 1?

Today, I read about info threads and a few other GDB commands, but I have never used GDB this way. 

https://gist.github.com/gbudny/55c9b887cfec555d0a9d504e537dea4a

Please. Let me know if these files aren't enough for you to fix. In this case, I will probably need the example to do it correctly.

**Comment by smallmodel** [comment]
Try again with the latest commit. Also try with the latest artifacts in the GitHub actions of the project

**Comment by gbudny** [comment]
Hi

Thank you for the answer.

I don't have any errors with libmad when I compile OpenMoHHA, but only a warning, which is probably nothing serious.

Unfortunately, I have the same issue when I try to run the most recent version of OpenMoHAA.

I uploaded new files to Wetransfer:

https://we.tl/t-XP2Y4uPEyx

I tried the latest version from the artifacts and have the same problem.

OpenMoHAA only works if I don't use the parameter - DUSE_SOUND_NEW=1.

Can you fix it?

**Comment by smallmodel** [comment]
Send the dump but with binaries otherwise the dump can't be debugged (binary mismatch)

**Comment by gbudny** [comment]
Thank you.

The game works, and this music issue is solved now.

However, I have a slightly different issue with OpenMoHAA. I will send all the files tomorrow in the newly opened issue.
