### ISSUE TITLE
(MoHAA/Spearhead/Breakthrough) OpenMoHAA starts too slow when I build it with the parameter -DUSE_SOUND_NEW=1

### ISSUE THREAD

**Issue by gbudny** [openmoh/openmohaa#333]
Hi

I want to inform you that OpenMoHAA starts too slow when I build it with the parameter -DUSE_SOUND_NEW=1. I see the black screen for 3-5 seconds, and then I see a main menu.

I uploaded all new files:

https://we.tl/t-KHOvqvei2S

Can you fix it?

**Comment by smallmodel** [comment]
Unfortunately this won't be fixable right now, openmohaa doesn't support streamed sounds. All sounds are loaded synchronously on memory. Original MOHAA loads streamed sounds like MP3 sounds asynchronously, it prevents hiccups like on openmohaa.
Compiling in release mode (optimized code) should reduce the delay

**Comment by gbudny** [comment]
Hi

Thank you for the answer.

I noticed a few other similar problems, but this issue isn't a place to discuss all of them separately. I will create separate issues for all of them soon. Maybe it won't be necessary, and you will find a solution. 

I will try to build it in Release mode, but I'm not sure if it will help me. 

The new sound system slows down OpenMoHAA on modern computers. It solves some problems, but it has very high requirements. It reminded me of Doom 3 on the old PC with Pentium4/RAM: 2GB/GeForce FX to give you a better example. The game often
stops for 1-2 seconds, or I can't move.

Do you think it's possible to make the new sound system work faster on modern computers?

**Comment by gbudny** [comment]
Hi

I built it in Release mode, and now the game starts in 1-2 seconds, which is a nice improvement. However, it doesn't solve this issue in Debug mode.

Unfortunately, OpenMoHAA has similar performance issues to those in a debug version.

**Comment by smallmodel** [comment]
Try to test the experimental streaming feature by using this branch: [features/oal-streaming](https://github.com/openmoh/openmohaa/tree/features/oal-streaming)

It works for me, but it will need more testing, need to check for crashes and errors.

**Comment by gbudny** [comment]
> Try to test the experimental streaming feature by using this branch: [features/oal-streaming](https://github.com/openmoh/openmohaa/tree/features/oal-streaming)
> 
> It works for me, but it will need more testing, need to check for crashes and errors.

Hi

I will check this version and start to report bugs when I find them.

**Comment by gbudny** [comment]
Thank you.

It works now.
