### ISSUE TITLE
(Spearhead/Breakthrough) Music doesn't work in the credits with the new sound system.

### ISSUE THREAD

**Issue by gbudny** [openmoh/openmohaa#334]
Hi

I want to inform you that music doesn't work in the credits when I build OpenMoHAA with the parameter -DUSE_SOUND_NEW=1.

I uploaded new files:

Spearhead:

https://we.tl/t-eLRjVz2Z2k

Breakthrough:

https://we.tl/t-3N3UZEuW71

Can you fix it?

**Comment by smallmodel** [comment]
> Couldn't load sound: sound/music/thuringer.mp3

Check `maintt/sound/music/thuringer.mp3`: I believe that's because the sound file has a capital `T` in the name, the Linux filesystem is case-sensitive. Unfortunately a fix in openmohaa directly is not possible, it's a mistake that has to be fixed in `ubersound.scr` by setting `Thuringer.mp3` instead

**Comment by gbudny** [comment]
> I don't have the issue on Windows, but on Linux it behaves differently.
> 
> > Couldn't load sound: sound/music/thuringer.mp3
> 
> Check the file `maintt/sound/music`: That must be because the sound file has a capital `T` in the name and the Linux filesystem is case-sensitive. Unfortunately a fix in openmohaa directly may not possible, it's a mistake that has to be fixed in `ubersound.scr` by setting `Thuringer.mp3` instead, or by renaming the music file but it will cause an issue for scripts that use the correct name

Hi

Thank you for the answer.

I didn't want to change the content of pak because other similar projects don't do it. On the other hand, It would probably require the other application to unpack it. I changed the name of this file, and it works now, but you mentioned it could cause other issues.

The old sound system system knows how to handle these slight differences in the names of files. I suspect there is a part of a source code that solves these problems.

Do you think the new sound system could be modified to "ignore" differences in the names of files like in the old one?
