### ISSUE TITLE
(MoHAA - the new sound system) Music doesn't work after I use shortcuts alt-tab and alt-enter

### ISSUE THREAD

**Issue by gbudny** [openmoh/openmohaa#336]
Hi

I want to inform you that the music in the credits stops working after I use shortcuts alt-tab and alt-enter. It happens when I build OpenMoHAA with the parameter -DUSE_SOUND_NEW=1.

EDIT:

I checked the most recent version of OpenMoHAA, but I still have the same problem. In this case, I have to create another issue.I tried to use shortcuts when it happened, so the output from a terminal is below:

https://gist.github.com/gbudny/37a2026828bc6b301fe9c2eeaf48e2a3

Can you fix it?

**Comment by gbudny** [comment]
Hi

I had to change a title because it also happens when I load a level and use one of these two shortcuts. I'm sorry, but I didn't check it out before I created this issue.

**Comment by smallmodel** [comment]
Does it works now?

**Comment by gbudny** [comment]
Hi

Thank you for the answer.

I checked it, and it still doesn't work when I use shortcuts:

https://gist.github.com/gbudny/b4b7fdbd8ee7e4efb57b3fae27d7c723

I see something like this when I switch between modes:

```
FIXME: Allow reverb toggle at runtime in OpenAL code.
tty]AL lib: (EE) ALCpulsePlayback_streamStateCallback: Received stream failure!
```

**Comment by smallmodel** [comment]
Try with different OpenAL backends:
```
ALSOFT_LOGLEVEL=3 ALSOFT_DRIVERS=backend_name ./openmohaax86_64-dbg
```
backend_name is one of the following values: jack, pulse, alsa, sndio, oss, port, null, wave

**Comment by gbudny** [comment]
Hi

I quickly checked all of them, and I can say that I have this issue when I use pulse. 

I don't have this problem using alsa, oss, and port. The sound is tranquil with sndio. 

The sound doesn't work with jack, null, and wave.

I uploaded files for all of them:

https://we.tl/t-pO8OaJqe3m

Can you fix this issue?

**Comment by smallmodel** [comment]
I don't think it's fixable because it may be due to pulse audio closing the device when unfocused
But you can try to use libopenal provided with openmohaa (it also has support for PipeWire), you can the latest build artifact from [GitHub Action](https://github.com/openmoh/openmohaa/actions) **Build**

**Comment by gbudny** [comment]
Hi

Thank you for the answer.

> I don't think it's fixable because it may be due to pulse audio closing the device when unfocused. In this case execute the command `snd_restart` in console.

It works.

Can you add this workaround to restart sound automatically when shortcuts are used? 

> However you can try to use libopenal provided with openmohaa (it also has support for PipeWire), you can the latest build artifact from [GitHub Action](https://github.com/openmoh/openmohaa/actions) **Build**

I tried this version, and it has the same problem.

**Comment by smallmodel** [comment]
Would you be able to try https://github.com/kcat/openal-soft using the master branch?
then: `ALSOFT_LOGLEVEL=3 ALSOFT_DRIVERS=pipewire ./openmohaax86_64-dbg` then send the logs.

Also try the following:
`SDL_VIDEODRIVER="wayland" ./openmohaax86_64-dbg`

**Comment by gbudny** [comment]
Thank you for the answer.

> Would you be able to try https://github.com/kcat/openal-soft using the master branch? then: `ALSOFT_LOGLEVEL=3 ALSOFT_DRIVERS=pipewire ./openmohaax86_64-dbg` then send the logs.

I built it, but I had some unresolved issues with libssl-dev, AudioIO, and some libraries are too old.  The sound doesn't work when I use this command ALSOFT_LOGLEVEL=3 ALSOFT_DRIVERS=pipewire. It only works when I type LD_PRELOAD=libopenal.so ./openmohaax86_64-dbg. 

> Also try the following: `SDL_VIDEODRIVER="wayland" ./openmohaax86_64-dbg`

I tried it, but the OpenMoHAA doesn't start when I do it.

**Comment by gbudny** [comment]
Thank you.

It works now.
