### ISSUE TITLE
Erorr build arm64

### ISSUE THREAD

**Issue by ArtemS2** [openmoh/openmohaa#338]
/home/artem/builds/openmohaa/code/script/scriptcompiler.cpp:35:10: fatal error: ../parser/generated/yyParser.hpp: Нет такого файла или каталога
   35 | #include "../parser/generated/yyParser.hpp"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [code/server/fgame/CMakeFiles/fgame.dir/build.make:104: code/server/fgame/CMakeFiles/fgame.dir/__/script/scriptcompiler.cpp.o] Ошибка 1
make[1]: *** [CMakeFiles/Makefile2:522: code/server/fgame/CMakeFiles/fgame.dir/all] Ошибка 2
make[1]: *** Ожидание завершения заданий…

**Comment by smallmodel** [comment]
On Linux, you must install the packages `flex` and `bison`

**Comment by ArtemS2** [comment]
I really forgot to deliver. Now everything works.
