### ISSUE TITLE
menu bug 

### ISSUE THREAD

**Issue by ArtemS2** [openmoh/openmohaa#344]
Some barely noticeable black highlights appeared above the active menu items
![Снимок экрана от 2024-08-24 06-54-48](https://github.com/user-attachments/assets/f947c98f-6b20-4bbc-afb7-1738833b8d6c)

**Comment by smallmodel** [comment]
set `r_forceClampToEdge` to 1

**Comment by ArtemS2** [comment]
Unfortunately, it didn't help (

**Comment by ArtemS2** [comment]
Thank you, everything worked out
