### ISSUE TITLE
(Spearhead - t1|2) OpenMoHAA freezes when I try to load a quick save

### ISSUE THREAD

**Issue by gbudny** [openmoh/openmohaa#345]
Hi

I noticed that OpenMoHAA (built with GCC) freezes during loading in level t1|2 when I try to use quick saves. It always happens when I quit a game and try rerunning it with quick saves.

I uploaded the files:

https://we.tl/t-9aqnMTnreO

Can you fix it?

**Comment by smallmodel** [comment]
Does it works now?

**Comment by gbudny** [comment]
Thank you for the answer.

I rechecked it, but it crashed during loading of this level. 
I uploaded files for the most recent version:

https://we.tl/t-St2AE1jme2

Can you fix it?

**Comment by gbudny** [comment]
Thank you.

It works now.
