### ISSUE TITLE
(AA - m5l2a) reversed projectile

### ISSUE THREAD

**Issue by bulldozerecske** [openmoh/openmohaa#346]
Projectile shot by NPC is flying from Panzerschrek in a reversed angle.

![image](https://github.com/user-attachments/assets/137f4e62-3f54-4aba-a841-d93300b6fc2a)

Version: OpenMoHAA 0.70.0-alpha+491.3733761 win_msvc64-x86_64 Sep 02 2024 UTC

**Comment by smallmodel** [comment]
This is an issue with the model itself, it was fixed in mohaas 2.0
