### ISSUE TITLE
(AA - m2l3) cannot shoot through ventillation grill

### ISSUE THREAD

**Issue by bulldozerecske** [openmoh/openmohaa#348]
Bullet is blocked when I try to shoot through the ventillation grill.
In Vanilla, it works.

![image](https://github.com/user-attachments/assets/90ced320-59e3-4ea5-8627-efb058c47c87)

Version: OpenMoHAA 0.70.0-alpha+491.3733761 win_msvc64-x86_64 Sep 02 2024 UTC

**Comment by gbudny** [comment]
Hi

I can confirm this problem also exists on Linux. I started to notice this issue when the bug below was fixed:

https://github.com/openmoh/openmohaa/issues/320
