### ISSUE TITLE
(AA - m6l1c) cannot shoot through opening in the wall

### ISSUE THREAD

**Issue by bulldozerecske** [openmoh/openmohaa#350]
Neither I nor the NPC could shoot through the opening in the wall.

![image](https://github.com/user-attachments/assets/bf0b03c7-9a1e-4518-ba6f-c30be6b78360)

Version: OpenMoHAA 0.70.0-alpha+491.3733761 win_msvc64-x86_64 Sep 02 2024 UTC

**Comment by smallmodel** [comment]
same bug as #348

**Comment by gbudny** [comment]
Thank you.

It works.
