### ISSUE TITLE
(Breakthrough - e1|2) Some areas of the ground aren't correctly displayed

### ISSUE THREAD

**Issue by gbudny** [openmoh/openmohaa#356]
Hi

I want to inform you that some areas of the ground aren't correctly displayed when I shoot. I noticed this bug also happens when soldiers are shooting or during explosions.

I created a video to show some areas where this issue exists when I use guns:

https://we.tl/t-yHXSW67HZI

Ubuntu 22.04

Can you fix it?

**Comment by smallmodel** [comment]
As a temporary workaround, disable **real dynamic lighting** in the advanced graphic options

**Comment by gbudny** [comment]
Hi

Thank you for the answer.

I checked this temporary workaround, and it solved this issue.

Do you plan to turn off this option in the default config files generated when OpenMoHAA runs for the first time?

**Comment by gbudny** [comment]
Thank you.

It works now.
