### ISSUE TITLE
Not an issue , but a question.

### ISSUE THREAD

**Issue by darkstar252** [openmoh/openmohaa#357]
Is possible to compile openmohaa for intel mac platforms??

**Comment by gbudny** [comment]
Hi

It was possible to compile the older versions because @sharpSteff had done it. I don't know if you can run and play OpenMoHAA after it:

https://github.com/openmoh/openmohaa/issues/123

**Comment by smallmodel** [comment]
Duplicate, see #123

**Comment by gbudny** [comment]
Hi

Does this issue also exist in OpenMoHAA on Linux PowerPC?
