### ISSUE TITLE
(MoHAA/Spearhead/Breakthrough) The sound disappears when I turn off/on the real dynamic lighting

### ISSUE THREAD

**Issue by gbudny** [openmoh/openmohaa#358]
Hi

I want to inform you that sound disappears in OpenMoHAA when I turn off/on the real dynamic lighting. Additionally, the screen is black for 1-2 seconds when I click the button Apply even if I use the same screen resolution in MATE and OpenMoHHA.

Below is the example when I turn it off in Breakthrough:

https://we.tl/t-19vMMlkczE

Can you fix it? 

Ubuntu 22.04

**Comment by smallmodel** [comment]
Same as #336
