### ISSUE TITLE
In-game Taunts Don't Work

### ISSUE THREAD

**Issue by mohaa-man** [openmoh/openmohaa#373]
In-game taunt menus hang, in that they don't accept keyboard input...you can pull up the menu, but you're supposed to be able to e.g. push a number to get a specific taunt, but this doesn't work.  The only way I've found to get rid of the menu is to vid_restart, switch maps, etc., but the taunt cannot be triggered.

 - OS: arch linux x86_64
 - OS Version: latest (rolling release), kernel 6.10.10-arch1-1
 - OpenMoHAA Version: 0.70.0-alpha+20.0a90757 (Sep 2 2024)

**Comment by SagarChandra07** [comment]
download

https://mega.co.nz/#!qq4nATTK!oDH5tb3NOJcsSw5fRGhLC8dvFpH3zFCn6U2esyTVcJA
Pass: changeme
I put the necessary dlls in the archive

**Comment by smallmodel** [comment]
I believe commit ffc3580d43d4b0c9c059a38784211c83780ca8b2 fixed it
