### ISSUE TITLE
Visible seams in main GUI/menus, and in rendered sky

### ISSUE THREAD

**Issue by mohaa-man** [openmoh/openmohaa#375]
**Describe the bug**
There are visible seams in the main menu/GUI that sometimes move or go away, as if along rectangular tile(s).  Some seams are horizontal, some vertical.  Their appearance/placement seems to shift in part due to potential math errors in display scaling.  When navigating through the GUI (e.g. from Main GUI to Multiplayer menu, model/skin selection, etc.), the display scaling/alignment shifts slightly up and/or down, implying perhaps a boresighting or FOV calculation rounding inconsistency.  This causes seams to appear/disappear and or change locations.

**To Reproduce**
1. Launch the game (I'm using 2560x1600 resolution)
2. Navigate through various GUI menus and observe seams
3. Pass cursor over various GUI elements; note seams appear around various changed GUI elements (e.g. the "Multiplayer" door gets a black box around it when it brightens, this should not happen)
4. Play a multiplayer map, and observe the sky; various prominent seams are always visible

**Expected behavior**
There shouldn't be visible black lines/seams/gaps in the GUI, nor in the sky.

**Screenshots (OPTIONAL)**

![Screenshot from 2024-09-28 22-02-06](https://github.com/user-attachments/assets/1b2e4f4f-22b4-423f-b11a-708a6345045f)
![Screenshot from 2024-09-28 22-01-44](https://github.com/user-attachments/assets/16da0fb9-27b5-4b2a-b967-d2355b8e4453)
![Screenshot from 2024-09-28 22-01-42](https://github.com/user-attachments/assets/5120fd42-b0e7-4eba-a160-829aa3c08625)

**Version information (please complete the following information):**
 - OS: arch linux x86_64
 - OS Version: latest (rolling release), kernel 6.10.10-arch1-1, nvidia 560.35.03-6 (RTX 3070 Max-Q laptop)
 - OpenMoHAA Version: 0.70.0-alpha+20.0a90757 (Sep 2 2024)

**Additional context (OPTIONAL)**
I have tried toggling the "Use Conformant Texture Clamping" option in the nVidia Settings panel, this has no effect.  The original EA version running in WINE did not exhibit this behavior at this resolution (nor at 2560x1440, the only two I tried).  Admittedly it was running on the AMD iGPU (5800h/Vega 8) in WINE, as I could never get it to run on the nVidia.

**Comment by SagarChandra07** [comment]
download
https://bit.ly/47P0Nvo
Pass: changeme

you may need to install the c compiler

**Comment by mohaa-man** [comment]
As suggested by pryon in Discord, 'r_forceClampToEdge 1' does improve this a lot; the sky issue seems to go away, and *most* of the issues in the GUI go away as well, although thin outlines are still visible around certain GUI elements.  I have attached a SS of the GUI; note the thin box around the spinning fan near the cursor:

![Screenshot from 2024-09-28 22-22-17](https://github.com/user-attachments/assets/ddc7ffbc-304c-4966-b807-171b67ab32c3)

**Comment by smallmodel** [comment]
Fixed in commit 047a7bb949fef3a036f854c0df68109038b846ec
