### ISSUE TITLE
(SH - m5l2b) incorrect naming

### ISSUE THREAD

**Issue by bulldozerecske** [openmoh/openmohaa#389]
If I play m5l2b in SpearHead, tank type refers to T34 instead of King Tiger.

![image](https://github.com/user-attachments/assets/b0dfa1f1-e5eb-4245-823b-57200a688eb3)

Version: OpenMoHAA 0.71.0-unstable+53.020a6d8 win_msvc64-x86_64 Sep 30 2024 UTC

**Comment by smallmodel** [comment]
This is not an engine issue, there could be some mods replacing "King Tiger" with "T34" in the localization file

**Comment by bulldozerecske** [comment]
> This is not an engine issue, there could be some mods replacing "King Tiger" with "T34" in the localization file

I have only this in mainta folder.
![image](https://github.com/user-attachments/assets/40c54aa1-901a-453e-903d-bdb00508164d)

**Comment by smallmodel** [comment]
Spearhead replaces `global/vehicle_thinkers.scr`, the script prints "The T34 tank has been lost, you have failed." so it's the correct behavior

**Comment by bulldozerecske** [comment]
> Spearhead replaces `global/vehicle_thinkers.scr`, the script prints "The T34 tank has been lost, you have failed." so it's the correct behavior

You're right and I should use the appropriate target game to run AA SinglePlayer levels. :)

**Comment by bulldozerecske** [comment]
> Spearhead replaces `global/vehicle_thinkers.scr`, the script prints "The T34 tank has been lost, you have failed." so it's the correct behavior

You're right and I should use the appropriate target game to run AA SinglePlayer levels. :)
