### ISSUE TITLE
(SH & BT - mohdm1) blinking foliage

### ISSUE THREAD

**Issue by bulldozerecske** [openmoh/openmohaa#395]
Foliage goes dark and bright from different angles.
It is NOT an issue in AA (openmohaa).

![image](https://github.com/user-attachments/assets/fddf2fee-13cb-4ee4-95b3-d04f89a5e9c4)

![image](https://github.com/user-attachments/assets/ad161aa1-fdb2-4d98-b5bb-61d1c2837a8c)

Version: OpenMoHAA 0.71.0-unstable+65.56f850b win_msvc64-x86_64 Oct 01 2024 UTC

**Comment by smallmodel** [comment]
It can't be fixed in the engine, it's an issue with the shader (textures/wilderness/jh_foliage2 in wilderness.shader), in SH/BT "surfaceparm fence" was replaced "surfaceparm wood" which makes the shader two-sided rather than front-sided and causes z-fighting

**Comment by smallmodel** [comment]
This must be fixed by modifying assets
