### ISSUE TITLE
Demo support?

### ISSUE THREAD

**Issue by neuromancer** [openmoh/openmohaa#40]
Hi,

I was wondering if you plan to support [the demo](https://archive.org/details/MedalOfHonourAlliedAssaultSinglePlayer), which could be useful for people to play some part of the game using this engine, without the need to buy the full game.

**Comment by smallmodel** [comment]
openmohaa should already work with demo assets

**Comment by neuromancer** [comment]
What we can expect to see when we run the client with the demo assets?

**Comment by smallmodel** [comment]
Nothing special, there must be no compatibility issues, and the full version of the client/server don't expect anything in the pk3 file that is only present in the full game.
