### ISSUE TITLE
sequenced packet without connection

### ISSUE THREAD

**Issue by bulldozerecske** [openmoh/openmohaa#400]
I had tried to connect to a server which is running UBER MODS and map loading stuck at 3/4 of the loading bar. Console floods:

`195.140.213.123:sequenced packet without connection`

Version: OpenMoHAA 0.71.0-unstable+70.23e56e7 win_msvc64-x86_64 Oct 02 2024 UTC

**Comment by smallmodel** [comment]
The message is normal, the server tries to send you game data but your client is not connected, it also happens in vanilla
