### ISSUE TITLE
(MoHAA) Cheat codes turn off the intro

### ISSUE THREAD

**Issue by gbudny** [openmoh/openmohaa#402]
Hi

I want to inform you when OpenMoHAA runs with cheat codes it turns off the intro. After that, the intro doesn't work when I try to run a game with or without cheat codes.

I can make the intro work again, but only when I remove a folder .openmohaa.

I attached files:

https://we.tl/t-r99ts6WG7P

Can you fix it? 

Ubuntu 22.04

This bug also exists in Spearhead and Breakthrough, but I decided to report first the issue for a base game.

**Comment by smallmodel** [comment]
The intro is skipped when `developer` is set to 1, it's the expected behavior from mohaa

**Comment by gbudny** [comment]
> The intro is skipped when `developer` is set to 1, it's the expected behavior from mohaa

Thank you for the answer.

It explains one specific behavior of OpenMoHAA, which means the intro isn't displayed when I run it in this way:

./openmohaax86_64-dbg +set developer 2 +set thereisnomonkey 1 +set cheats 1 +set ui_console 1c


However, the intro is permanently turned off when I don't use any parameters. 

 ./openmohaax86_64-dbg

It always happens when I use this parameter only time:

./openmohaax86_64-dbg +set developer 2 +set thereisnomonkey 1 +set cheats 1 +set ui_console 1c

In this case, I must remove the folder .openmohaa to see the intro again.

Is it the normal behavior of OpenMoHAA?

**Comment by smallmodel** [comment]
the value of `developer` is saved in the user configuration, just set the `developer` value to 0

**Comment by gbudny** [comment]
Thank you for the answer.

In all three configs, the developer set value was changed from 0 to 2 when I used cheat codes — it was a parameter that I used. I changed it from 2 to 0 to fix the issue with all intros.

I would be great if OpenMoHAA could automatically change this value from 1 or 2 to 0 in the config files if it's runs without any parameters.

./openmohaax86_64-dbg

Do you plan add it?

**Comment by smallmodel** [comment]
No, this variable is saved in the config file like in the original game, so modders can skip intro. The intro can be time-consuming during development

**Comment by gbudny** [comment]
Thank you for the answer.

I understand your decision to make OpenMoHAA similar to the original game.

I decided to close this issue.
