### ISSUE TITLE
Problem with the lights, a strange glitch in the mission briefing and a question

### ISSUE THREAD

**Issue by SilentMRG** [openmoh/openmohaa#407]
Hello everyone!

Well, let's get straight to the point... Starting with the briefing for the first mission, a strange bug/glitch occurs making the compass + health bar visible on the screen.

The second bug was noticed in the first mission, the lights on the truck do not illuminate the ground correctly and the textures are blinking on the ground, I also noticed that when shooting in the first mission the ground texture also blinks, apparently the light effect is broken.

I don't know if I was clear with the information, and I hope this helps in some way.
Now I have a question: Does the source port support expansions? If so, how do I execute them?

Thank you for your attention...
Best regards!

**Comment by bulldozerecske** [comment]
Which version did u play?
You should download the latest build from **Actions** (not the released one).
You can find the current version number at the very top of the console.
Also, please provide screenshots or videos if you report an issue! Thank you!

**Comment by SilentMRG** [comment]
> Which version did u play?

GOG version.

**Comment by bulldozerecske** [comment]
> > Which version did u play?
> 
> GOG version.

I mean... which openmohaa version....

**Comment by SilentMRG** [comment]
> I mean... which openmohaa version....

I'm using "v0.70.0-alpha".

And if it helps I'm on a potato laptop with Windows 7 64 bit with an Intel HD Graphics.

Unfortunately, I don't have images or videos about the issues mentioned in the other post, so it will be up to someone to test and try to reproduce what I described.

Thank you for your attention;
Best regards!
