### ISSUE TITLE
(AA - m4l2) blinking truck wheel textures

### ISSUE THREAD

**Issue by bulldozerecske** [openmoh/openmohaa#416]
I've just noticed that the wheels have some texture issue at this scene.

https://github.com/user-attachments/assets/5b8b1632-fda2-44ba-9738-0030a901726e

Version: OpenMoHAA 0.71.0-unstable+131.5ea90eb win_msvc64-x86_64 Oct 18 2024 U

**Comment by smallmodel** [comment]
It's a problem with the TIKI model itself (same issue in OG), the model doesn't specify a surface for the "moving tread" so the default texture is used
