### ISSUE TITLE
REAME Location of files in hidden folder .moh

### ISSUE THREAD

**Issue by gbudny** [openmoh/openmohaa#44]
Hi

What files should be added to the folders Main and OpenMoHAA in the hidden folder .moh?

I added cgamex86_64.so and gamex86_64.so to both folders to prevent the game from crashing when I try to load basic training or multiplayer. It doesn't help with the singleplayer campaign. 

Do I need to add other files to the Main and OpenMoHAA folders?

**Comment by smallmodel** [comment]
Those are the only files.

Also, singleplayer isn't stable, the focus is currently multiplayer

**Comment by smallmodel** [comment]
Added to README

The singleplayer mode is kinda hard to do as the script engine is not in a stable state, it's definitely not easier although I fixed a few things

**Comment by gbudny** [comment]
> Added to README
> 
> The singleplayer mode is kinda hard to do as the script engine is not in a stable state, it's definitely not easier although I fixed a few things

Hi

Thank you for the answer.

I'm happy with every change that you are making to this project.

I want to share a small suggestion with you if you don't mind.

Have you thought about developing the single-player mode gradually?

I think about starting with simple tasks.

For example. can you add the possibility to load the maps from Mohaa as you did with the basic training? I can walk from the beginning to the end of the map, which is awesome!

Later, you can fix trivial things like missing objects or incorrect areas. Many tasks in mohaa are like finding a document or loading the next level after finding a specific place. 

Many users could appreciate that every release of Openmohha is more playable. In other words, the game will become a more functional project for users interested in the single-player mode.

**Comment by Alex3474247** [comment]
It would be great if you make the single player mode fully playable. For example, for me there is no MoHAA without a single player, it's a long, interesting campaign (Omaha Beach, etc), but the original MoHAA engine has serious speeding and mouse issues because this is a DirectX game and it's no longer playable on modern systems (Windows 10, 11 etc).

**Comment by gbudny** [comment]
Hi

It's great to see more people interested in this game.
Smallmodel make this project so incredible.
Recently, you can play the basic training, which is great.
I noticed that the first minute of Arzew is displayed when you start it, then game crashes - it's stil the alpha version.

The Windows version isn't so bad.

The Windows version isn't so bad.

I'm keeping the computer with Pentium 4 processor and the Linux distribution from 2003 (Linux 2.4) to play the native Linux version. It's Beta 3 version of the game that was never finished. In this case, you don't have intro, and it's limited to the base version. It crashes in the same locations on every Linux distribution with kernel higher than 2.6.7. You frequently don't hear when enemies shoot to you, and I have turn on subtitles because voices of other soldiers don't work most of the time. Ryan Gordon did excellent job by porting this game to Linux, but I think he didn't get paid for his work. It's a shame that EA only contracted him to port Linux servers for Medal of Honor. He did what he could to work on it in his spare time for above a year. Unfortunately, we have this unofficial version for Linux that doesn't work on the modern computers. This project can solve this issue.

It's funny that I like this game so much that I get used to all issues with the Linux version of Mohaa.
 
The Mac version doesn't work on anything higher than Mac OS X 10.6 from 2009.

**Comment by gbudny** [comment]
I can close this issue because Openmohaa doesn't require having libraries in multiple locations. 

Thank you.
