### ISSUE TITLE
(SH - t3l1) mortar works only at lowest firing angle

### ISSUE THREAD

**Issue by bulldozerecske** [openmoh/openmohaa#442]
I noticed that in OpenMohaa, if you shoot with the mortar at this scene, it fires projectile only at the lowest firing angle (to the farthest distance).

https://github.com/user-attachments/assets/36e10476-9db2-4d45-83ff-532c62f4221a

Version: OpenMoHAA 0.71.0-unstable+143.13885ae win_msvc64-x86_64 Oct 20 2024 UTC

**Comment by smallmodel** [comment]
Should be fixed by 3d454c90cb046bc66c1e327c8cd2e11e02065bfe
