### ISSUE TITLE
crash when closing console

### ISSUE THREAD

**Issue by bulldozerecske** [openmoh/openmohaa#458]
I launched OpenMohaa (SH) then I put it to taskbar with windows key then I closed the console and I got an exception in VS 2022.

![image](https://github.com/user-attachments/assets/2d861a42-bf23-4f32-be75-4876a578f7b7)

Version: OpenMoHAA 0.71.0-unstable+168.8ecbe1d win_msvc64-x86_64 Oct 21 2024 UTC

**Comment by smallmodel** [comment]
That's because the signal is received and processed from another thread which leads to a race condition. This could be reported upstream https://github.com/ioquake/ioq3
