### ISSUE TITLE
What version of Medal of Honor: Allied Assault War Chest do you use?

### ISSUE THREAD

**Issue by gbudny** [openmoh/openmohaa#46]
Hi

I have a question for people that develop this project.

What version of Medal of Honor: Allied Assault War Chest do you use?

I have crashes during loading maps in the multiplayer mode with Breakthrough that I don't have with the base game and Spearhead. Maybe there are some differences in the GOG version.

**Comment by smallmodel** [comment]
The US version.

It seems that pak0-pak5 files are different between languages. The Warchest build has pak0-pak5 files that is different from the US copy.
So the pure check was disabled

**Comment by smallmodel** [comment]
It should work with any language now
