### ISSUE TITLE
(BT) flashing limbs and weapon while mounting mortar

### ISSUE THREAD

**Issue by bulldozerecske** [openmoh/openmohaa#474]
When I mount a mortar, player's limbs and its weapon flash for a second. It only occurs if I do it on a dedicated (openmohaa) server.

https://github.com/user-attachments/assets/3aad4fe4-b1ac-4262-8835-2d27214e7403

Version: OpenMoHAA 0.71.0-unstable+195.edb52a8 win_msvc64-x86_64 Oct 23 2024 UTC

**Comment by smallmodel** [comment]
It also occurs on vanilla and on a vanilla breakthrough server. This will only be fixed client-side.
