### ISSUE TITLE
explosion/smoke fx fully rendered through barbwire

### ISSUE THREAD

**Issue by bulldozerecske** [openmoh/openmohaa#479]
I've just noticed that the smoke following the grenade explosion is visible through the wire part of the texture, no matter how far the detonation is. Tested on Omaha Beach.

![image](https://github.com/user-attachments/assets/3dfcacf9-12ae-476c-9865-44bcc073ba4d)

Version: OpenMoHAA 0.80.0-unstable+215.bf68808 win_msvc64-x86_64 Oct 28 2024 UTC

**Comment by smallmodel** [comment]
This is an issue with the `static_bspindle` shader (from static_obstacles.shader), it blends and it doesn't write depth information so this has to be fixed in the shader
