### ISSUE TITLE
cursor position zeroed when disconnect from game

### ISSUE THREAD

**Issue by bulldozerecske** [openmoh/openmohaa#482]
If I click on the button "Disconnect from game" the cursor goes to the top left corner which is a little bit annoying.

https://github.com/user-attachments/assets/00a0b36f-3552-40af-85fe-f0786c30a364

Version: OpenMoHAA 0.80.0-unstable+215.bf68808 win_msvc64-x86_64 Oct 28 2024 UTC

**Comment by smallmodel** [comment]
This also occurs in the original game, it's an easy fix
