### ISSUE TITLE
(AA - Modern Warfare Total Conversion) allied pistol not firing properly

### ISSUE THREAD

**Issue by bulldozerecske** [openmoh/openmohaa#496]
Allied pistol has no muzzle flash and the firing sound can be heard only once when you switch to the weapon. In Vanilla, it is not an issue.

https://github.com/user-attachments/assets/21ba7167-d863-42da-b26c-813cf151a995

Version: OpenMoHAA 0.80.0-unstable+228.48fa5c0 win_msvc64-x86_64 Oct 28 2024 UTC

**Comment by smallmodel** [comment]
Fix
