### ISSUE TITLE
(SH/BT Demo) could not load default.cfg

### ISSUE THREAD

**Issue by bulldozerecske** [openmoh/openmohaa#517]
SH and BT demos could not be launched with OpenMoHAA.

```
C:\Program Files (x86)\EA GAMES\Medal of Honor Allied Assault Spearhead Demo/main

----------------------
0 files in pk3 files
Couldn't load default.cfg

C:\Program Files (x86)\EA GAMES\Medal of Honor Allied Assault Spearhead Demo\openmohaa.x86_64.exe (process 11604) exited with code 3 (0x3).
```

Folder looks like this:
![image](https://github.com/user-attachments/assets/19a5b201-a20f-47d9-abc5-3ef01d3c917d)

Version: OpenMoHAA 0.80.0-unstable+277.9a64722 win_msvc64-x86_64 Nov 13 2024 UTC

**Comment by smallmodel** [comment]
Start the game in [demo mode](https://github.com/openmoh/openmohaa/blob/main/docs/getting_started_running.md#playing-with-the-downloadable-demo)

**Comment by bulldozerecske** [comment]
![image](https://github.com/user-attachments/assets/549bdb12-742b-4da8-898a-90569067fa65)

**Comment by smallmodel** [comment]
Don't forget `+set com_target_game 1` (or 2)
