### ISSUE TITLE
Clientside project for cmake?

### ISSUE THREAD

**Issue by TomArrow** [openmoh/openmohaa#53]
I might just be too inexperienced, but when I generate the Visual Studio projects I seem to be missing anything client game related. For example the file cl_parse.cpp appears to be missing from the entire solution, I can't find stuff that should be in it when I do a global search. To give an example, svc_snapshot is referenced only twice in the solution, once in the enum and once the serverside writing. But nowhere do I see the parsing.

The release does include the client though, so I'm not sure what I'm doing wrong. It must be possible to compile it no?

**Comment by smallmodel** [comment]
GitHub actions is able to compile the project successfully, meaning anyone else can compile.
`cl_parse.cpp` is in the source tree

**Comment by TomArrow** [comment]
I think I see what the problem was.

The client stuff is hidden behind ```if (WITH_CLIENT)``` and WITH_CLIENT isn't defined by default, but it is defined in the Github Actions config.

The CMake GUI doesn't show that option.

I'm not an expert in CMake at all but I'm guessing to show the option (and maybe turn it on by default) one would have to add

```set(WITH_CLIENT TRUE)```

somewhere in the CmakeLists.txt file. Either way, with setting it manually I do get the client project, so all good. Just a lil something for more userfriendliness I guess.

**Comment by smallmodel** [comment]
`WITH_CLIENT` was when the client code was in an unstable state, only the server code was properly implemented.
Now that the client code is working well, the variable was renamed to `BUILD_NO_CLIENT` instead, so it can be explicitly excluded from build.
