### ISSUE TITLE
Shooting oil barrels doesn't show oil leaking out

### ISSUE THREAD

**Issue by mohaa-man** [openmoh/openmohaa#532]
**Describe the bug**
Shooting an oil barrel should result in an animation of the oil leaking out onto the surface beneath it, but nothing happens.

**To Reproduce**
1. Load up the V2 multiplayer map (there are several oil barrels by the rocket)
2. Shoot a barrel in the side
3. See no oil leaking out.

**Expected behavior**
Oil should leak out for several seconds (longer times expected if you shoot the bottom of the barrel vs. the top, or if you shoot it a 2nd time below the 1st hole it should leak some more).

**Screenshots (OPTIONAL)**
Don't have a SS, but can get one if it would help.

**Logs**
Nothing of consequence in the logs.

**Version information (please complete the following information):**
 - Arch Linux (latest, 6.11.9-arch1-1 kernel)
 - OpenMoHAA Version: latest release [0.70.0-alpha] for Linux

**Dump (OPTIONAL)**
N/A

**Additional context (OPTIONAL)**
N/A

**Comment by smallmodel** [comment]
A lot of the bugs were fixed in the master branch including barrel bugs. The latest build can be downloaded from [here](https://github.com/openmoh/openmohaa/actions) (Build branch)

**Comment by mohaa-man** [comment]
Can confirm this works in the latest build.
