### ISSUE TITLE
build failure at 6fe1e86 on fedora 41 x86_64

### ISSUE THREAD

**Issue by bf2006a** [openmoh/openmohaa#539]
Fatal error:

...

[626/684] Building C object code/client/cgame/CMakeFiles/cgame.dir/cg_main.c.o
FAILED: code/client/cgame/CMakeFiles/cgame.dir/cg_main.c.o 
/usr/bin/gcc -DCGAME_DLL -DNDEBUG -Dcgame_EXPORTS -I/tmp/openmohaa/code/qcommon/../qcommon -I/tmp/openmohaa/code/qcommon/../script -I/tmp/openmohaa/.cmake/code/qcommon/generated -fPIC -Wno-comment -Werror=return-type -fno-gnu-unique -MD -MT code/client/cgame/CMakeFiles/cgame.dir/cg_main.c.o -MF code/client/cgame/CMakeFiles/cgame.dir/cg_main.c.o.d -o code/client/cgame/CMakeFiles/cgame.dir/cg_main.c.o -c /tmp/openmohaa/code/cgame/cg_main.c
/tmp/openmohaa/code/cgame/cg_main.c: In function ‘CG_GetRendererConfig’:
/tmp/openmohaa/code/cgame/cg_main.c:573:35: error: passing argument 1 of ‘cgi.UI_GetHighResolutionScale’ from incompatible pointer type [-Wincompatible-pointer-types]
  573 |     cgi.UI_GetHighResolutionScale(&cgs.uiHiResScale);
      |                                   ^~~~~~~~~~~~~~~~~
      |                                   |
      |                                   vec_t (*)[2] {aka float (*)[2]}
/tmp/openmohaa/code/cgame/cg_main.c:573:35: note: expected ‘vec_t *’ {aka ‘float *’} but argument is of type ‘vec_t (*)[2]’ {aka ‘float (*)[2]’}
[629/684] Building CXX object code/client/cgame/CMakeFiles/cgame.dir/cg_commands.cpp.o
/tmp/openmohaa/code/cgame/cg_commands.cpp: In member function ‘void ClientGameCommandManager::StopLoopSound(Event*)’:
/tmp/openmohaa/code/cgame/cg_commands.cpp:4149:38: warning: converting to non-pointer type ‘sfxHandle_t’ {aka ‘int’} from NULL [-Wconversion-null]
 4149 |     current_centity->tikiLoopSound = NULL;
      |                                      ^~~~
ninja: build stopped: subcommand failed.

Full transcript attached.
[openmohaa_6fe1e86_build_failure_gcc_14.2.1_fedora41_x86_64_20241130.txt](https://github.com/user-attachments/files/17967200/openmohaa_6fe1e86_build_failure_gcc_14.2.1_fedora41_x86_64_20241130.txt)

**Comment by smallmodel** [comment]
Should be good now
