### ISSUE TITLE
Web3 OpenMohaa

### ISSUE THREAD

**Issue by pdr76** [openmoh/openmohaa#54]
Many games are migrating to Web3, in fact, one example is the work done by Lattice (https://twitter.com/latticexyz?lang=es), creating OpCraft (https://github.com/tenetxyz/opcraft- redstone) a Minecraft Web3 clone, I think it would be a good idea to offer you the idea of developing OpenMohaa on Web3.

**Comment by smallmodel** [comment]
Won't happen, openmohaa will stay on the Quake engine
