### ISSUE TITLE
Water/Ocean wave sound effect corrupt/missing

### ISSUE THREAD

**Issue by hellodub** [openmoh/openmohaa#547]
**Describe the bug**
In certain parts of the campaign where the ocean wave sound effect is supposed to play, only static/white noise is heard. This has happened in at least two parts of the campaign so far. It was first encountered at the lighthouse approach during the Arzew mission, and then again during the beginning sequence of the beach landing in the Omaha Beach mission. 

**To Reproduce**
Play any campaign map where there is a waterfront, or where waves should be crashing.

**Expected behavior**
The ocean wave splash sound effect plays instead of white noise/static

**Screenshots (OPTIONAL)**
I've attached a clip of the beginning of the Omaha Beach mission that demonstrates the bug, below:

https://github.com/user-attachments/assets/6bc39570-bf0d-4241-98cc-9602c0ee09b0

**Logs**
[qconsole.log](https://github.com/user-attachments/files/18032211/qconsole.log)

**Version information (please complete the following information):**
 - OS: Pop!_OS
 - OS Version:  22.04 LTS
 - OpenMoHAA Version: OpenMoHAA 0.80.0-beta+1.586da44 (Medal of Honor: Allied Assault 1.12) linux-x86_64 Nov 24 2024 UTC

**Additional context (OPTIONAL)**

The console is spamming the error "WARNING: Failed to open sound sound/null.wav!"
Seems like the game is looking for a non-existent sound file, which is probably why it plays white noise instead.

**Comment by smallmodel** [comment]
It has been fixed in commit 1e9decf19320eafd01f7221a91f8e41a1756cef5
