### ISSUE TITLE
Compile with renderergl2 from Linux Arm with Opengl ES 2.0

### ISSUE THREAD

**Issue by KorolevSoftware** [openmoh/openmohaa#558]
Hi, I want to compile the engine for OpenGL ES 2.0, there is a new renderer in the sources, but renderergl2 don't have CMakeLists. Can you help me?
I make CMakeLists for renderergl2, but is emit frag memory.
And I remove QuatSlerp in q_math for compile with renderergl2.
[CMakeLists.txt](https://github.com/user-attachments/files/18051560/CMakeLists.txt)

**Comment by smallmodel** [comment]
renderergl2 is not supported yet, the code directly came from upstream (ioq3) and needs some heavy modifications to make it mohaa-compatible, so only renderergl1 is supported currently

**Comment by KorolevSoftware** [comment]
OK, thank you!

**Comment by yaing11** [comment]
> renderergl2 is not supported yet, the code directly came from upstream (ioq3) and needs some heavy modifications to make it mohaa-compatible, so only renderergl1 is supported currently

but, sir, ioq3 already has rendererql2 option using BUILD_RENDERER_OPENGL2 var. Can we move this solution to mohaa?

**Comment by smallmodel** [comment]
It will have an option once GL2 gets supported and is able to renderer mohaa assets/UI
