### ISSUE TITLE
/qcommon/str.h:592: void str::tolower(): Assertion `m_data' failed.

### ISSUE THREAD

**Issue by gbudny** [openmoh/openmohaa#56]
Hi

I wanted to check many interesting changes in the most recent version of Openmohaa. Unfortunately, I noticed the same bug that exists when I try to load Basic training, Credits, and maps in the multiplayer mode (Mohaa, Spearhead, Breakthrough).

Ubuntu 22.04

https://gist.github.com/gbudny/2d24e766fd1e13e19392e045093c755e

**Comment by smallmodel** [comment]
Fetch the latest commits, append `-DCMAKE_BUILD_TYPE=Debug -DDEBUG_DROP_ASSERT=1` to the CMake command-line and try again

**Comment by gbudny** [comment]
Thank you for the answer.

I have the same issue with the most recent version of Openmohaa. I decided to build it again with your parameter to CMake:

https://gist.github.com/gbudny/ac5b360b45fda942b51889796486b7b4

**Comment by gbudny** [comment]
It's fixed now.

Thank you for your hard work on the basic training.  
I can't believe that I played it with Openmohaa!

I have other issues with Credits and all maps in Breakthrough that crash the game. I start to report them tomorrow with the new version of Openmohaa.
