### ISSUE TITLE
FOV does not persist between level change or loading from a saved game

### ISSUE THREAD

**Issue by hellodub** [openmoh/openmohaa#575]
**Describe the bug**
Changing the value of 'fov' does not last between missions, restarting mission on death, or from loading a saved game. The variable "fov" always returns to the default value of 80.  I'm using an 34" 21:9 ultrawide monitor, so a value of 110 is what I need.

In addition, setting the FOV in the player's "omconfig.cfg" does nothing when adding "seta cg_fov x" (which is probably the incorrect variable). Interestingly, using "seta fov x" (in my case "seta fov 110") causes the game to report the FOV "110" as default, but it isn't. This also makes setting the FOV inside the game with the console no longer work, no matter what value you enter.

**To Reproduce**
Open console and type "fov x" where x is your desired field of view in degrees or add "seta fov x" to player's omconfig.cfg file.

**Expected behavior**
Set the variable "fov" to however many degrees you need and it persists through missions, restarts, or saved games.

**Screenshots (OPTIONAL)**
> Default FOV when loading a saved game
![openmohaa-default-fov](https://github.com/user-attachments/assets/70465d36-0699-45ec-bc37-45f2f0c08036)

> Setting FOV to 110 through the console
![openmohaa-custom-fov](https://github.com/user-attachments/assets/65027687-e991-4c40-ae5b-b1ec43785906)

> Adding "seta fov 110" in my omconfig.cfg file causes fov to report 110 as the default, but is actually an FOV of 80
![openmohaa-default-fov-config](https://github.com/user-attachments/assets/b0fd877a-1f38-4638-ac55-5360f52a3ec1)

> Trying to change the value of "fov" now does nothing, no matter what value I enter. Setting the FOV through the console becomes effective again by removing "seta fov 110" from my omconfig.cfg file, but does not solve the value not persisting between missions/saved games/restarts
![openmohaa-fov-no-change](https://github.com/user-attachments/assets/c81850c9-6f47-4c82-ab6b-d6f1af06dea7)

**Logs**
[qconsole.log](https://github.com/user-attachments/files/18141538/qconsole.log)

**Version information (please complete the following information):**
 - OS: Pop!_OS
 - OS Version 22.04
 - OpenMoHAA Version: OpenMoHAA 0.80.0-beta+1.586da44 (Medal of Honor: Allied Assault 1.12) linux-x86_64 Nov 24 2024 UTC

**Comment by bulldozerecske** [comment]
I use it as: `bind x "fov 110"`. But yes, it should be persistent. Although, I noticed that in MP if you lean into the wall you are able to see through it (not sure if you can see the players, too).

**Comment by hellodub** [comment]
> I use it as: `bind x "fov 110"`. But yes, it should be persistent. Although, I noticed that in MP if you lean into the wall you are able to see through it (not sure if you can see the players, too).

Hah, didn't think about doing that, thanks for the tip. But I should mention that this is for the campaign/single-player, I understand why this might not be allowed in MP and that's ok
