### ISSUE TITLE
(Breakthrough) Palermo doesn't load

### ISSUE THREAD

**Issue by gbudny** [openmoh/openmohaa#58]
Hi

I noticed that the map Palermo doesn't load properly, and gets stuck in the middle of loading.
I had to force this game to quit.

https://gist.github.com/gbudny/70c65f4eeb77e8cd9e441890828de517

**Comment by smallmodel** [comment]
it has probably been fixed with the set of commits, I didn't encounter any issue

**Comment by gbudny** [comment]
Hi

I checked the most recent version of Openmohaa, and it works now.

Thank you.
