### ISSUE TITLE
Slight spelling mistake in death messages?

### ISSUE THREAD

**Issue by TomArrow** [openmoh/openmohaa#59]
I noticed some slight differences to the base game in the death messages:

https://github.com/openmoh/openmohaa/blob/25c417187bf66cbfbe5f300c6ce1c3126c1c5d78/code/fgame/player.cpp#L2735-L2742

https://github.com/openmoh/openmohaa/blob/25c417187bf66cbfbe5f300c6ce1c3126c1c5d78/code/fgame/player.cpp#L2770

e.g.
```"'s' shrapnel out of his teeth"```

instead of

```"'s shrapnel out of his teeth"```

(extra single quote)

Or is this something that later versions of the game/extensions changed?

**Comment by smallmodel** [comment]
fixed
