### ISSUE TITLE
Improvement idea: Interpolate fLeanAngle for demo playback

### ISSUE THREAD

**Issue by TomArrow** [openmoh/openmohaa#66]
So, when playing back demos at fps that are higher than the sv_fps of the server it was recorded on (or with lower timescale), any leaning is kinda stuttery. It's not in normal gameplay (probably because of clientside prediction code that doesn't run for demo playback) but it is when playing back demos. I think this can be solved by interpolating fLeanAngle the same way that origin, viewangles and origin is interpolated for the playerstate, when playing back demos (or possibly if first person spectating but not sure). 

Just a tiny possible improvement over the normal game which has the same "problem".

**Comment by smallmodel** [comment]
Should be fixed. Also fixed the viewmodel always looking like jumping if there is no prediction

**Comment by TomArrow** [comment]
> Should be fixed. Also fixed the viewmodel always looking like jumping if there is no prediction

Nice find! Out of curiosity, a question regarding this:

https://github.com/openmoh/openmohaa/commit/d5e93d863a5ac09f73f2fae87039f5781ecab8f8

Was there a reason to do this in CG_TransitionSnapshot? And back when it was in CG_InterpolatePlayerStateCamera, did you at any point notice a sort of "flickering" in the view model animation by any chance?
