### ISSUE TITLE
(Credits) munmap_chunk(): invalid pointer DOUBLE SIGNAL FAULT: Received signal 6, exiting...

### ISSUE THREAD

**Issue by gbudny** [openmoh/openmohaa#68]
Hi

I checked the most recent version of Openmohaa. I noticed it always freezes the game when I press the left mouse button to skip credits.

openmohaax86_64-dbg

https://gist.github.com/gbudny/e9c1cedcff3ca543934983477a4c061f

I know that Openmohaa became more unstable and crashed in different places more frequently 2 or 3 days before you released version 0.5.80.

**Comment by smallmodel** [comment]
#65

**Comment by gbudny** [comment]
Thank you.

It works now.
