### ISSUE TITLE
(Basic training) All tents are invisible

### ISSUE THREAD

**Issue by gbudny** [openmoh/openmohaa#69]
Hi

I noticed that in the most recent version all tents are invisible. There are more similar issues on invisible objects in the basic training.

Do you want me to add a list of all of them here?

or 

Do you want me to report one by one in the separated issues?

**Comment by smallmodel** [comment]
Commit b3371b2d63e4e4e5ef86b8ec680f7fc9371a0dd5 fixed the issue.

**Comment by gbudny** [comment]
Thank you.

It works now.
