### ISSUE TITLE
(Breakthrough) Game frequently crashes when I don't use GDB

### ISSUE THREAD

**Issue by gbudny** [openmoh/openmohaa#75]
Hi

I have this weird issue with Openmohaa. I have random crashes, when I load the Basic training or Rangers Lead the Way. It frequently crashes when I try load a movie from Breakthrough, and I think it's the same bug.

I tried to catch this bug many times, and it always works fine when I use GDB, which is weird.

https://gist.github.com/gbudny/8c7203fd31de2e2d4baf35ab9b1e32f3

Can you help me?

**Comment by smallmodel** [comment]
It should be fixed now

**Comment by gbudny** [comment]
Thank you.

I checked the new version, and it doesn't crash now in all the situations that I mentioned.
