### ISSUE TITLE
(Spearhead) Press fire to continue - the game crashes when I try to reload it

### ISSUE THREAD

**Issue by gbudny** [openmoh/openmohaa#81]
Hi

I checked the new version of Openmohaa.
I noticed that Spearhead always crashes when I click a left mouse button to continue after Jack Barnes dies.

Can you fix it?

A terminal output and the file core.dmp:

https://we.tl/t-7Fy6N4Xfe1

**Comment by smallmodel** [comment]
Game saving/loading should now be fixed in the latest commit

**Comment by gbudny** [comment]
Thank you.

I will check it out when this issue would be solved because I can't build it now:

https://github.com/openmoh/openmohaa/issues/83

**Comment by gbudny** [comment]
Thank you.

It works now.
