### ISSUE TITLE
Plans for the secret level M410

### ISSUE THREAD

**Issue by gbudny** [openmoh/openmohaa#84]
Hi

Maplist is needed to load the level M410. I didn't know it existed for many years.

Do you plan to make changes in the process of loading this level in Openmohaa?

Do you plan to keep it hidden like in an original game?

It's a fun level.

https://www.youtube.com/watch?v=1uB6xOFlQM0 

M410 isn't part of the whole campaign, just like basic training. You can check off M410 from a list if you decide to finish it before other missions.

**Comment by smallmodel** [comment]
Maplist is now implemented, since commit eb7d01b3e7a7a708d1aeef4677b3955b40be7dfc

**Comment by gbudny** [comment]
Hi

Thank you for adding it.

I understand it's the early version of maplist.

How can I use it?

I typed maplist, but I didn't see any graphical window. In this case, I typed in the console: maplist name_of_a_map (with. bsp and without .bsp).

**Comment by gbudny** [comment]
Hi

Thank you!

I made a mistake.

I forgot to update my installation script, so I was constantly downloading the old version from Pyron. 

#!/bin/sh
cd '/home/gbudny/Medal of Honor - Allied Assault War Chest'
rm o* *.so
cd
rm -Rf openmohaa
git clone https://github.com/openmoh/openmohaa
cd openmohaa/build
cmake .. -DCMAKE_BUILD_TYPE=Debug -DDEBUG_DROP_ASSERT=1 -DDEBUG_MEMORY=1
make
cp o* '/home/gbudny/Medal of Honor - Allied Assault War Chest'
cd code/client/cgame
cp cgamex86_64-dbg.so '/home/gbudny/Medal of Honor - Allied Assault War Chest'
cd ../../../
cd code/server/fgame
cp gamex86_64-dbg.so '/home/gbudny/Medal of Honor - Allied Assault War Chest'
cd 

The maplist and the level M410 work now.
