### ISSUE TITLE
(Spearhead) texture and model rendering

### ISSUE THREAD

**Issue by bulldozerecske** [openmoh/openmohaa#94]
In SH, on mp_holland, you can see the terrain through the windows and sometimes the sunshaded tables are not rendered properly (disappear-reappear).
![omoh_mp_holland_issue_01](https://github.com/openmoh/openmohaa/assets/8028500/41961313-c472-4747-b9d5-bb70ca8f5619)
![omoh_mp_holland_issue_02](https://github.com/openmoh/openmohaa/assets/8028500/8bcad653-9e58-4a45-8438-7419305d8431)

**Comment by smallmodel** [comment]
Fixed in commit 51ba1e295104385c9b00ad476f3cd936c855464c

**Comment by bulldozerecske** [comment]
> Fixed in commit [51ba1e2](https://github.com/openmoh/openmohaa/commit/51ba1e295104385c9b00ad476f3cd936c855464c)

sunshaded tables still an issue in Breakthrough
