### ISSUE TITLE
player gets stuck

### ISSUE THREAD

**Issue by bulldozerecske** [openmoh/openmohaa#96]
In AA, on Remagen, player gets stuck in the roof of the balcony while jumping.
![image](https://github.com/openmoh/openmohaa/assets/8028500/5adbf519-8c25-4cb8-8f14-6a6c6ec02a3d)

**Comment by bulldozerecske** [comment]
Same issue on objteam3...
![image](https://github.com/openmoh/openmohaa/assets/8028500/6009d770-fbc8-4693-9584-4b6f325da44a)

**Comment by smallmodel** [comment]
Fixed in commit 748934edcd35e3bde7506f676a1aabbdffaab81a
